import React from 'react';

export const review = (screenshots) => (
    <div className='review-content'>
        <div className="review-meRambling">
            <p class="review-section-subtitle"># me rambling</p>
            <p>Arrietty is a film about growing up and beginning your own exploration of the world, but is also a film about discovering new ways of living, integrating humanity with nature, finding positives out of negatives, and generally about the ever-changing perspectives of life and how that evolves as you gather more life experience.</p>
            <p>It never resorted to petty narrative cliches despite so many opportunities to do so (like many U-rated animation films these days).</p>
            <p>Explores similar themes to Kikis Delivery Service (a young mind venturing out into a big scary world), except with Arrietty the world is literally massive, and the characters are tiny!</p>
            <img src={screenshots[0]} alt="Screenshot from film" />
            <p>Ontop of all the thematic depth and character development, the whole experience of the film is like a beutiful moving painting, every frame looks amazing. It doesn't look like it was generated by an AI but clearly has a lot of attention to detail and rich in colour. Even the cinematography was amazing, really emphasing the difference in size and perspectives.</p>
            <p>Asks questions about how humanity can become more integrated with nature, instead of fighting it for our own selfish needs. It did this without seeming preachy, but rather compassionate and thought-provoking (similar thoughts to Nausicaa).</p>
            <p>The idea of loads of little human creatures creating their own tiny habitats inside the walls of a house, a world that looks so magical when you're inside it, but so tiny and insignificant when seeing it from their perspective. And this is obviously real! Think about how much wildlife exists just in your garden! So many interesting stories about nature, and how our existence can either harm them or benefit them.</p>
            <img src={screenshots[1]} alt="Screenshot from film" />
        </div>
        <div className="review-synopsis">
            <p class="review-section-subtitle"># brief synopsis</p>
            <p>A family of tiny people live anonymously in another family's residence, borrowing simple items to make their home. Life changes for the tiny people when Arrietty, is discovered.</p>
            <img src={screenshots[2]} alt="Screenshot from film" />
        </div>
    </div>
)