/**
 * Local album review data
 */

import ReactDomServer from 'react-dom/server';

import { review as YesFlyFromHereReview } from '../websiteContent/albums/yes-fly_from_here/review.jsx';
import { review as BocMHTRTCReview } from '../websiteContent/albums/boards_of_canada-music_has_the_right_to_children/review.jsx';
import { review as ChisatoYamadaReview } from '../websiteContent/albums/chisato_yamada-suite_nihonkai/review.jsx';


export const albumReviews = [
    {
        lastFmUrl: "https://www.last.fm/music/Yes/Fly+From+Here",
        rymUrl: "https://rateyourmusic.com/release/album/yes/fly-from-here/",
        youtubeUrl: "https://www.youtube.com/watch?v=SEs-i9kMpKg",
        yearOfRelease: "2011",
        genres: ["Progressive rock; Symphonic prog; Progressive pop"],
        customCoverUrl: "https://e.snmc.io/i/600/w/24fff9fba3db9be267f1db022618451f/3764571/yes-fly-from-here-Cover-Art.jpg",
        myRating: "10",
        myReview: ReactDomServer.renderToString(YesFlyFromHereReview()),
        myDiscoveryYear: "2013"
    },
    {
        lastFmUrl: "https://www.last.fm/music/XTC/Mummer",
        rymUrl: "https://rateyourmusic.com/release/album/xtc/mummer/",
        youtubeUrl: "",
        yearOfRelease: "2011",
        genres: ["Art punk; New wave; Art rock; Psychdelic pop; Neo-Psychedelia"],
        myRating: "10",
        customCoverUrl: "https://beatopolis.files.wordpress.com/2019/01/xtc-1.jpg?w=640",
        myDiscoveryYear: "2013"
    },
    {
        lastFmUrl: "https://www.last.fm/music/Boards+of+Canada/Music+Has+the+Right+to+Children",
        rymUrl: "https://rateyourmusic.com/release/album/boards-of-canada/music-has-the-right-to-children/",
        youtubeUrl: "",
        yearOfRelease: "1998",
        genres: ["IDM; Ambient; Downtempo"],
        themes: ["Atmospheric", "Otherworldy", "Mysterious", "Vast", "Dark", "Nostalgic", "Ethereal", "Creepy", "Weird", "Surreal"],
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2017",
        customCoverUrl: "https://bocpages.org/w/images/Music_Has_the_Right_to_Children.jpg",
        myReview: ReactDomServer.renderToString(BocMHTRTCReview()),
    },
    {
        lastFmUrl: "https://www.last.fm/music/Orbital/In+Sides",
        rymUrl: "https://rateyourmusic.com/release/album/orbital/in-sides/",
        youtubeUrl: "",
        yearOfRelease: "1997",
        genres: ["Ambient techno; IDM; Ambient; Breakbeat; Progressive Breaks; Neo-Psychedelia"],
        themes: [""],
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2017",
        customCoverUrl: "https://f4.bcbits.com/img/a1871008282_10.jpg",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Boards+of+Canada/Random+35+Tracks+Tape",
        rymUrl: "https://rateyourmusic.com/release/unauth/boards-of-canada/random-35-tracks-tape/",
        youtubeUrl: "",
        yearOfRelease: "1996",
        genres: ["IDM; Ambient; Breakbeat"],
        customCoverUrl: "https://i1.sndcdn.com/artworks-MCKqEy3UB0Ye9PdD-sI6suA-t500x500.jpg",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2017"
    },
    {
        lastFmUrl: "https://www.last.fm/music/Ichiko+Aoba/Windswept+Adan",
        rymUrl: "https://rateyourmusic.com/release/album/%E9%9D%92%E8%91%89%E5%B8%82%E5%AD%90/%E3%82%A2%E3%83%80%E3%83%B3%E3%81%AE%E9%A2%A8-windswept-adan/",
        youtubeUrl: "",
        yearOfRelease: "2020",
        genres: ["J-folk; Chamber folk; Ambient; New age; Nature recordings; J-acoustic"],
        customCoverUrl: "https://m.media-amazon.com/images/I/71Q93PPdn0L._UF894,1000_QL80_.jpg",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2021",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Radiohead/In+Rainbows",
        rymUrl: "https://rateyourmusic.com/release/album/radiohead/in-rainbows/",
        youtubeUrl: "",
        yearOfRelease: "2007",
        genres: ["Art rock; Dream pop; Art pop; Alternative rock"],
        customCoverUrl: "https://m.media-amazon.com/images/I/A1MwaIeBpwL._UF894,1000_QL80_.jpg",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2017",
    },
    {
        lastFmUrl: "https://www.last.fm/music/System+of+a+Down/Hypnotize",
        rymUrl: "https://rateyourmusic.com/release/album/system-of-a-down/hypnotize/",
        youtubeUrl: "",
        yearOfRelease: "2005",
        genres: ["Alternative Metal; Avant-garde Metal"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/a96a0ff1cd9b384659b7edac19dc15b6.jpg#a96a0ff1cd9b384659b7edac19dc15b6",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2010",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Daft+Punk/Discovery",
        rymUrl: "https://rateyourmusic.com/release/album/daft-punk/discovery/",
        youtubeUrl: "",
        yearOfRelease: "2001",
        genres: ["French House; Electro-Disco; Funky House; Dance pop; Synth Funk; Nu-disco"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/54010ae7c4fa4c96a1e1872a051d9ecc.jpg#54010ae7c4fa4c96a1e1872a051d9ecc",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2020",
    },
    {
        lastFmUrl: "https://www.last.fm/music/The+Dukes+Of+Stratosphear/Chips+From+The+Chocolate+Fireball",
        rymUrl: "https://rateyourmusic.com/release/comp/the-dukes-of-stratosphear/chips-from-the-chocolate-fireball/",
        youtubeUrl: "",
        yearOfRelease: "1987",
        genres: ["Psychedelic Rock; Psychedelic Pop; Jangle pop; New wave"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/42a3dd8c1dea4f35b3c0711eb02c1a9d.jpg#42a3dd8c1dea4f35b3c0711eb02c1a9d",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2012",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Radiohead/A+Moon+Shaped+Pool",
        rymUrl: "https://rateyourmusic.com/release/album/radiohead/a-moon-shaped-pool/",
        youtubeUrl: "",
        yearOfRelease: "2016",
        genres: ["Art rock; Chamber pop; Ambient pop; Art pop"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/28db3fdca036fb53c62754694a89d3fd.jpg#28db3fdca036fb53c62754694a89d3fd",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2016",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Linkin+Park/Hybrid+Theory",
        rymUrl: "https://rateyourmusic.com/release/album/linkin-park/hybrid-theory/",
        youtubeUrl: "",
        yearOfRelease: "2000",
        genres: ["Art rock; Chamber pop; Ambient pop; Art pop"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/cc15ebc58ec625979776cabaaaa282fa.jpg#cc15ebc58ec625979776cabaaaa282fa",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2016",
    },
    {
        lastFmUrl: "https://www.last.fm/music/alt-J/An+Awesome+Wave",
        rymUrl: "https://rateyourmusic.com/release/album/alt-j/an-awesome-wave/",
        youtubeUrl: "",
        yearOfRelease: "2012",
        genres: ["Indie pop; Art pop; Progressive Pop; Folktronica; Indietronica; Post-rock"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/ff6f2fe0511f4d25bf42cb8ab88ed2e2.jpg#ff6f2fe0511f4d25bf42cb8ab88ed2e2",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2013",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Asia/Gravitas",
        rymUrl: "https://rateyourmusic.com/release/album/asia/gravitas/",
        youtubeUrl: "",
        yearOfRelease: "2013",
        genres: ["Symphonic rock; Progressive rock; Art rock; AOR"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/fc4273ad9d904206c2776ca005d01e32.jpg#fc4273ad9d904206c2776ca005d01e32",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2014",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Poppy/EAT+(NXT+Soundtrack)",
        rymUrl: "https://rateyourmusic.com/release/ep/poppy/eat/",
        youtubeUrl: "",
        yearOfRelease: "2021",
        genres: ["Metalcore; Alternative metal; Nu Metal; Noise; Electropop; Screamo"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/263ef1af1dd0bea47e452cf4c75e681f.jpg#263ef1af1dd0bea47e452cf4c75e681f",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2021",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Enter+Shikari/The+Mindsweep",
        rymUrl: "https://rateyourmusic.com/release/album/enter-shikari/the-mindsweep/",
        youtubeUrl: "",
        yearOfRelease: "2015",
        genres: ["Post-hardcore; Drum and bass; Metalcore; Trancecore; Trance"],
        customCoverUrl: "https://www.nme.com/wp-content/uploads/2016/09/2014EnterShikari_TheMindSweep_081014.jpg",
        myRating: "10",
        myReview: "",
        myDiscoveryYear: "2016",
    },


    {
        lastFmUrl: "https://www.last.fm/music/Chisato+Yamada/Suite+Nihonkai+%E7%B5%84%E6%9B%B2%E3%80%8C%E6%97%A5%E6%9C%AC%E6%B5%B7%E3%80%8D%E6%B4%A5%E8%BB%BD%E3%81%98%E3%82%87%E3%82%93%E3%81%8B%E3%82%89%E6%B5%81%E3%82%8C%E7%AF%80",
        rymUrl: "https://rateyourmusic.com/release/album/%E5%B1%B1%E7%94%B0%E5%8D%83%E9%87%8C/suite_nihonkai_%E7%B5%84%E6%9B%B2%E3%80%8C%E6%97%A5%E6%9C%AC%E6%B5%B7%E3%80%8D%E6%B4%A5%E8%BB%BD%E3%81%98%E3%82%87%E3%82%93%E3%81%8B%E3%82%89%E6%B5%81%E3%82%8C%E7%AF%80/",
        youtubeUrl: "",
        yearOfRelease: "1981",
        genres: ["Tsugaru shamisen; Min'yō Music; J-acoustic; J-funk; Funk"],
        customCoverUrl: "https://lastfm.freetls.fastly.net/i/u/770x0/8d6f20e4ef9693e3c33f29ea141d591c.jpg#8d6f20e4ef9693e3c33f29ea141d591c",
        myRating: "9.5",
        myReview: "",
        myDiscoveryYear: "2021",
        myReview: ReactDomServer.renderToString(ChisatoYamadaReview()),
    },
    {
        lastFmUrl: "https://www.last.fm/music/%E4%B9%85%E7%9F%B3%E8%AD%B2/The+Wind+Rises+Soundtrack",
        rymUrl: "https://rateyourmusic.com/release/album/%E4%B9%85%E7%9F%B3%E8%AD%B2/%E9%A2%A8%E7%AB%8B%E3%81%A1%E3%81%AC_%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF__kaze_tachinu_soundtrack_/",
        youtubeUrl: "",
        yearOfRelease: "2013",
        genres: ["Movie soundtrack"],
        myRating: "9.0",
        customCoverUrl: "https://i.scdn.co/image/ab67616d0000b273c853c5a8535cc3dc394efc58",
        myReview: "",
        myDiscoveryYear: "2022",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Minseo/The+Diary+of+Youth",
        rymUrl: "https://rateyourmusic.com/release/ep/minseo/the-diary-of-youth/",
        youtubeUrl: "",
        yearOfRelease: "2019",
        genres: ["K-pop; Jazz; Jazz pop"],
        myRating: "8.25",
        myReview: "",
        myDiscoveryYear: "2023",
    },
    {
        lastFmUrl: "https://www.last.fm/music/Takashi+Kako/Shiki+Jitsu+(be+happy.+be+happy.+be+happy)",
        rymUrl: "https://rateyourmusic.com/release/album/takashi-kako/be-happy_be-happy_be-happy/",
        youtubeUrl: "",
        yearOfRelease: "2000",
        genres: ["Movie soundtrack; Neoclassical New Age; Ambient; Piano"],
        myRating: "9.75",
        myReview: "",
        myDiscoveryYear: "2023",
    },
    {
        lastFmUrl: "https://www.last.fm/music/World%27s+End+Girlfriend/Hurtbreak+Wonderland",
        rymUrl: "https://rateyourmusic.com/release/album/takashi-kako/be-happy_be-happy_be-happy/",
        youtubeUrl: "",
        yearOfRelease: "2007",
        genres: ["Post-Rock; Modern Classical; IDM; Breakcore; Glitch; Chamber jazz"],
        customCoverUrl: "https://e.snmc.io/i/1200/s/d47bc66835d87bec07db7789341d5fbc/10509124",
        myRating: "8.25",
        myReview: "",
        myDiscoveryYear: "2023",
    },
]
