/**
 * Local album review data.
 * The json is merged with the web data in /reducers/RootReducer.js
 */

import ReactDomServer from 'react-dom/server';
import { convert_collection_of_json_objects_to_one_list, convert_collection_of_json_objects_to_one_list_grouped_by_letters } from '../../js/helpers.js';

import { review as YesFlyFromHereReview } from '../websiteContent/albums/yes-fly_from_here/review.jsx';
import { review as BocMHTRTCReview } from '../websiteContent/albums/boards_of_canada-music_has_the_right_to_children/review.jsx';
import { review as ChisatoYamadaReview } from '../websiteContent/albums/chisato_yamada-suite_nihonkai/review.jsx';


/**
 * Album reviews database
 */
const database = {
	123: {
		"808_state__don_solaris": {
			lastfm_url: "https://www.last.fm/music/808+State/Don+Solaris",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1996",
			year_of_discovery: "2023",
			genres: ["Acid house; Drum and bass; Trip hop; Jungle; Breakbeat; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"4hero__two_pages": {
			lastfm_url: "https://www.last.fm/music/4hero/Two+Pages",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1998",
			year_of_discovery: "2023",
			genres: ["Jazz; Drum and bass; Nu jazz; Breakbeat; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},	
	},

	THE: {
		"the_future_sound_of_london__lifeforms": {
			lastfm_url: "https://www.last.fm/music/The+Future+Sound+of+London/Lifeforms",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/0UcHfoo7KMso767JwePBMh?si=41z25T5GSWuV0-7d2mFPpQ",
			year_of_release: "1994",
			year_of_discovery: "2023",
			genres: ["Ambient; Ambient techno; Techno; IDM; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"the_strokes__comedown_machine": {
			lastfm_url: "https://www.last.fm/music/The+Strokes/Comedown+Machine",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2013",
			year_of_discovery: "2014",
			genres: ["Indie rock; Post-punk revival; Alternative rock; Garage rock; New wave"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"the_drums__the_drums": {
			lastfm_url: "https://www.last.fm/music/The+Drums/The+Drums",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2010",
			year_of_discovery: "2014",
			genres: ["Indie pop; Surf music; Indie rock"],
			my_rating: 9.0,
			my_review: "",
		},

		"the_field__looping_state_of_mind": {
			lastfm_url: "https://www.last.fm/music/The+Field/Looping+State+of+Mind",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2011",
			year_of_discovery: "2023",
			genres: ["Minimal techno; Ambient techno; Tech house; Electronic"],
			my_rating: 8.5,
			my_review: "",
		},
			
		"the_bug__london_zoo": {
			lastfm_url: "https://www.last.fm/music/The+Bug/London+Zoo",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2008",
			year_of_discovery: "2021",
			genres: ["Dubstep; Ragga; Industrial Hip-Hop"],
			my_rating: 9.0,
			my_review: "",
		},

		"the_caretaker__everywhere_at_the_end_of_time": {
			lastfm_url: "https://www.last.fm/music/The+Caretaker/Everywhere+at+the+end+of+time",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2020",
			genres: ["Ambient; Dark ambient; Hauntology; Experimental"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	A: {
		"andreas_vollenweider__down_to_the_moon": {
			lastfm_url: "https://www.last.fm/music/Andreas+Vollenweider/Down+to+the+Moon",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2DM9WPZiokvkAm4Y7xqXjF?si=8H3b6UPJSAuszhCCIiX5Gg",
			year_of_release: "1986",
			year_of_discovery: "2023",
			genres: ["New age; Ambient; Progressive pop; Electronic"],
			my_rating: 9.5,
			my_review: "",
		},

		"andreas_vollenweider__dancing_with_the_lion": {
			lastfm_url: "https://www.last.fm/music/Andreas+Vollenweider/Dancing+With+The+Lion",
			rym_url: "https://rateyourmusic.com/release/album/andreas-vollenweider/dancing-with-the-lion/",
			spotify_url: "https://open.spotify.com/album/56EOamthibjth9GE7nr9Ko?si=xJ3Gzoz0Tem3qcpA-Rdv5g",
			year_of_release: "1989",
			year_of_discovery: "2023",
			genres: ["New age; Ambient; Neoclassical New Age"],
			my_rating: 8.0,
			my_review: "",
		},

		"andreas_vollenweider__white_winds": {
			lastfm_url: "https://www.last.fm/music/Andreas+Vollenweider/White+Winds+(Seeker%27s+Journey)",
			rym_url: "https://rateyourmusic.com/release/album/andreas_vollenweider/white_winds/",
			spotify_url: "https://open.spotify.com/album/56EOamthibjth9GE7nr9Ko?si=xJ3Gzoz0Tem3qcpA-Rdv5g",
			year_of_release: "1984",
			year_of_discovery: "2023",
			genres: ["New age; Ambient; Neoclassical New Age"],
			my_rating: 8.0,
			my_review: "",
		},
	
		"altJ__an_awesome_wave": {
			lastfm_url: "https://www.last.fm/music/alt-J/An+Awesome+Wave",
			rym_url: "https://rateyourmusic.com/release/album/alt-j/an-awesome-wave/",
			spotify_url: "https://open.spotify.com/album/6HbJlAnTRhWae1F3lEwGkv?si=o6DSFRHVRFCOXpm9K7kQLw",
			year_of_release: "2012",
			genres: ["Indie pop; Art pop; Progressive Pop; Folktronica; Indietronica; Post-rock"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/ff6f2fe0511f4d25bf42cb8ab88ed2e2.jpg#ff6f2fe0511f4d25bf42cb8ab88ed2e2",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2013",
		},
	
		"asia__gravitas": {
			lastfm_url: "https://www.last.fm/music/Asia/Gravitas",
			rym_url: "https://rateyourmusic.com/release/album/asia/gravitas/",
			spotify_url: "https://open.spotify.com/album/05ZncAfXCsmBH2UVx78gaL?si=rdS3CLWeSXSTO9YnxaRGIQ",
			year_of_release: "2013",
			genres: ["Symphonic rock; Progressive rock; Art rock; AOR"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/fc4273ad9d904206c2776ca005d01e32.jpg#fc4273ad9d904206c2776ca005d01e32",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2014",
		},

		"anna_meridith__varmints": {
			lastfm_url: "https://www.last.fm/music/Anna+Meredith/Varmints",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7IjNWdNec6pdPRU5aW5FI0?si=poySdx5qTGS2Ir-FyRrQiA",
			year_of_release: "2004",
			year_of_discovery: "2018",
			genres: ["Progressive pop; Synthpop; Dance pop; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"air__talkie_walkie": {
			lastfm_url: "https://www.last.fm/music/Air/Talkie+Walkie",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/0hQOqvZv1nQvPiBjzyn363?si=Qam-m3WEQMSBLyusjgEShw",
			year_of_release: "2004",
			year_of_discovery: "2018",
			genres: ["Ambient pop; Ambient; Downtempo; Synthpop; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"a_tribe_called_quest__the_low_end_theory": {
			lastfm_url: "https://www.last.fm/music/A+Tribe+Called+Quest/The+Low+End+Theory",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1991",
			year_of_discovery: "2017",
			genres: ["Hip-Hop; Rap; Jazz rap; Old-school Hip-Hop"],
			my_rating: 9.0,
			my_review: "",
		},

		"aphex_twin__selected_ambient_works_volume_ii": {
			lastfm_url: "https://www.last.fm/music/Aphex+Twin/Selected+Ambient+Works,+Volume+II",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1994",
			year_of_discovery: "2019",
			genres: ["Ambient; Dark ambient; Minimalism; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"air__moon_safari": {
			lastfm_url:"https://www.last.fm/music/Air/Moon+Safari",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1998",
			year_of_discovery: "2018",
			genres: ["Downtempo; Ambient; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"antonio_carlos_jobim__the_composer_of_desafinado_plays": {
			lastfm_url: "https://www.last.fm/music/Ant%C3%B4nio+Carlos+Jobim/The+Composer+of+Desafinado+Plays",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1963",
			year_of_discovery: "2023",
			genres: ["Jazz; Bossa nova; MBP; Latin jazz; Brazilian jazz"],
			themes: ["Brazilian"],
			my_rating: 9.0,
			my_review: "",
		},

		"altJ__this_is_all_yours": {
			lastfm_url: "https://www.last.fm/music/alt-J/This+Is+All+Yours",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2014",
			year_of_discovery: "2014",
			genres: ["Indie pop; Indie rock; Indietronica"],
			my_rating: 9.0,
			my_review: "",
		},

		"all_time_low__future_hearts": {
			lastfm_url: "https://www.last.fm/music/All+Time+Low/Future+Hearts",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2015",
			year_of_discovery: "2015",
			genres: ["Pop-punk"],
			my_rating: 8.5,
			my_review: "",
		},

		"air__10000_hz_legend": {
			lastfm_url: "https://www.last.fm/music/Air/10,000+Hz+Legend",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2001",
			year_of_discovery: "2018",
			genres: ["Ambient; Downtempo; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"a_tribe_called_quest__thank_you_4_your_service": {
			lastfm_url: "https://www.last.fm/music/A+Tribe+Called+Quest/We+Got+It+From+Here...+Thank+You+4+Your+Service",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2016",
			genres: ["Hip-Hop; Rap; Jazz rap"],
			my_rating: 8.5,
			my_review: "",
		},

		"arca__kick_ii": {
			lastfm_url: "https://www.last.fm/music/Arca/KICK+ii",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2015",
			year_of_discovery: "2015",
			genres: ["Reggaeton; Technocumbia; Breakbeat; Dance pop"],
			themes: ["Venezuela", "Spanish"],
			my_rating: 8.5,
			my_review: "",
		},

		"ask_my_bull__creature": {
			lastfm_url: "https://www.last.fm/music/Ask+My+Bull/CREATURE",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2019",
			year_of_discovery: "2023",
			genres: ["Jazz punk; Dance punk; Jazz; Punk"],
			themes: ["Visceral", "Catchy", "Memorable"],
			my_rating: 9.0,
			my_review: "",
		},

		"alexandre_desplat__the_shape_of_water_soundtrack": {
			lastfm_url: "https://www.last.fm/music/Alexandre+Desplat/The+Shape+Of+Water+(Original+Motion+Picture+Soundtrack)",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2021",
			genres: ["Film soundtrack; Ambient"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	B: {
		"brockhampton__saturation_iii": {
			lastfm_url: "https://www.last.fm/music/BROCKHAMPTON/SATURATION+III",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/5c2AzoNyr46fCQM5d8mxE0?si=lcsioOPXSKebGjw75Ii7uw",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["Hip-Hop; Rap"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"bring_me_the_horizon__thats_the_spirit": {
			lastfm_url: "https://www.last.fm/music/Bring+Me+the+Horizon/That%27s+the+Spirit",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2020",
			year_of_discovery: "2020",
			genres: ["Metalcore; Alternative rock; Pop rock; Alternative metal; Nu metal; Electronic rock"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"badbadnotgood__BBNG2": {
			lastfm_url: "https://www.last.fm/music/BADBADNOTGOOD/BBNG2",
			rym_url: "",
			youtube_url: "https://www.youtube.com/watch?v=l97mbF7J-r4&pp=ygUVYmFkYmFkbm90Z29vZF9fQkJORzIj",
			year_of_release: "2014",
			year_of_discovery: "2015",
			genres: ["Jazz; Jazz fusion; Nu jazz; Instrumental Hip-Hop"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"boards_of_canada__old_tunes_vol_2": {
			lastfm_url: "https://www.last.fm/music/Boards+of+Canada/Old+Tunes+Vol.+2",
			rym_url: "",
			youtube_url: "https://www.youtube.com/watch?v=Y9ShhIgBe7A&pp=ygUhYm9hcmRzX29mX2NhbmFkYV9fb2xkX3R1bmVzX3ZvbF8y",
			year_of_release: "1996",
			year_of_discovery: "2017",
			genres: ["Ambient; Ambient techno; IDM; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"beach_house__teen_dream": {
			lastfm_url: "https://www.last.fm/music/Beach+House/Teen+Dream",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7ejB3MHdDNcY3GzRsQRAHs?si=-oIBTQgJT56pvCoU_kPtsQ",
			year_of_release: "2010",
			year_of_discovery: "2022",
			genres: ["Dream pop; Indie pop; Indie rock; Shoegaze"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"badbadnotgood__IV": {
			lastfm_url: "https://www.last.fm/music/BADBADNOTGOOD/IV",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/5wAGlQICfKYQfaBppnUbmP?si=ehQl80M2TXK5Q7tG68TWwA",
			year_of_release: "2016",
			year_of_discovery: "2018",
			genres: ["Jazz; Hip-Hop; Instrumental Hip-Hop"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"bjork__post": {
			lastfm_url: "https://www.last.fm/music/Bj%C3%B6rk/Post",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3p7WXDBxhC5KS9IFXnwae7?si=GAhYw43FROKgEjtY7l5p4w",
			year_of_release: "1995",
			year_of_discovery: "2021",
			genres: ["Trip hop; Alternative pop; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"brand_new__science_fiction": {
			lastfm_url: "https://www.last.fm/music/Brand+New/Science+Fiction",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2Oyi0iQ92nw0MlO6ehpNwJ?si=WRw9HmAETjOenKBwO0kbLg",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["Emo; Alternative rock; Post-hardcore"],
			my_rating: 9.5,
			my_review: "",
		},
		
		"beach_house__once_twice_melody": {
			lastfm_url: "https://www.last.fm/music/Beach+House/Once+Twice+Melody",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2eTxZYoqIv4MoLqwh73qvo?si=RAL01RHJRtW5yTlTnF3cHQ",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Dream pop; Chamber pop; Neo-psychedelia"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"boards_of_canada__geogaddi": {
			lastfm_url: "https://www.last.fm/music/Boards+of+Canada/Geogaddi",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/4T7JGfRryhw5POaXalkApE?si=xSJGDU22TRuiZgHKN87g8A",
			year_of_release: "2002",
			year_of_discovery: "2016",
			genres: ["IDM; Ambient; Ambient techno; Downtempo; Electronic"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"bring_me_the_horizon__post_human_survival_horror": {
			lastfm_url: "https://www.last.fm/music/Bring+Me+the+Horizon/POST+HUMAN:+SURVIVAL+HORROR",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/0e1WaSNDZnoPixaxDNdWo4?si=SKRn8GwCQfqlcDlEMysY3w",
			year_of_release: "2020",
			year_of_discovery: "2020",
			genres: ["Alternative metal; Metalcore; Heavy metal; Nu metal"],
			my_rating: 10,
			my_review: "",
		},
	
		"boards_of_canada__mhtrtc": {
			lastfm_url: "https://www.last.fm/music/Boards+of+Canada/Music+Has+the+Right+to+Children",
			rym_url: "https://rateyourmusic.com/release/album/boards-of-canada/music-has-the-right-to-children/",
			custom_cover_url: "https://bocpages.org/w/images/Music_Has_the_Right_to_Children.jpg",
			spotify_url: "https://open.spotify.com/album/1vWnB0hYmluskQuzxwo25a?si=IHYW6vgvTha6CfUPDWsMzw",
			year_of_release: "1998",
			year_of_discovery: "2016",
			genres: ["IDM; Ambient; Downtempo; Electronic"],
			themes: ["Atmospheric", "Otherworldy", "Mysterious", "Vast", "Dark", "Nostalgic", "Ethereal", "Creepy", "Weird", "Surreal"],
			my_rating: 10,
			my_review: ReactDomServer.renderToString(BocMHTRTCReview()),
		},
	
		"boards_of_canada__random_30_tracks_tape": {
			lastfm_url: "https://www.last.fm/music/Boards+of+Canada/Random+35+Tracks+Tape",
			rym_url: "https://rateyourmusic.com/release/unauth/boards-of-canada/random-35-tracks-tape/",
			youtube_url: "https://www.youtube.com/watch?v=nSGIX0U8myU&t=8s&pp=ygUnYm9hcmRzX29mX2NhbmFkYV9fcmFuZG9tXzMwX3RyYWNrc190YXBl",
			year_of_release: "1996",
			genres: ["IDM; Ambient; Breakbeat; Electronic"],
			custom_cover_url: "https://i1.sndcdn.com/artworks-MCKqEy3UB0Ye9PdD-sI6suA-t500x500.jpg",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2017"
		},
	
		"boards_of_canada__a_few_old_tunes": {
			lastfm_url: "https://www.last.fm/music/Boards+of+Canada/A+Few+Old+Tunes",
			rym_url: "",
			youtube_url: "https://www.youtube.com/watch?v=_KvK0F860Xk&pp=ygUhYm9hcmRzX29mX2NhbmFkYV9fYV9mZXdfb2xkX3R1bmVz",
			year_of_release: "1996",
			year_of_discovery: "2017",
			genres: ["IDM; Ambient; Breakbeat; Electronic"],
			my_rating: 9.5,
			my_review: "",
		},

		"brand_new__deja_entendu": {
			lastfm_url: "https://www.last.fm/music/Brand+New/Deja+Entendu",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2003",
			year_of_discovery: "2015",
			genres: ["Post-hardcore; Emo; Alternative rock"],
			themes: ["Angsty", "Rebellious"],
			my_rating: 9.0,
			my_review: "",
		},

		"bon_iver__for_emma_forever_ago": {
			lastfm_url: "https://www.last.fm/music/Bon+Iver/For+Emma,+Forever+Ago",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2007",
			year_of_discovery: "2022",
			genres: ["Indie folk; Folk; Alternative country; Chamber folk"],
			my_rating: 8.5,
			my_review: "",
		},

		"bent__programmed_to_love": {
			lastfm_url: "https://www.last.fm/music/Bent/Programmed+to+Love",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2000",
			year_of_discovery: "2023",
			genres: ["Downtempo; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"bruno_sanfilippo__ver_sacrum": {
			lastfm_url: "https://www.last.fm/music/Bruno+Sanfilippo/Ver+Sacrum",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2023",
			year_of_discovery: "2023",
			genres: ["Ambient; Post-minimalism; Neo-classical new age; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"bruno_sanfilippo__unity": {
			lastfm_url: "https://www.last.fm/music/Bruno+Sanfilippo/Unity",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2018",
			year_of_discovery: "2023",
			genres: ["Ambient; Post-minimalism"],
			my_rating: 8.5,
			my_review: "",
		},

		"boards_of_canada__in_a_beautiful_place_out_in_the_country": {
			lastfm_url: "https://www.last.fm/music/Boards+of+Canada/In+a+Beautiful+Place+Out+in+the+Country",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2019",
			year_of_discovery: "2016",
			genres: ["Ambient; Downtempo; Electronic"],
			themes: ["Creepy", "Sinister", "Mysterious", "Relaxing"],
			my_rating: 9.0,
			my_review: "",
		},

		"boards_of_canada__the_campfire_headphase": {
			lastfm_url: "https://www.last.fm/music/Boards+of+Canada/The+Campfire+Headphase",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2005",
			year_of_discovery: "2017",
			genres: ["IDM; Downtempo; Ambient; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	},
	
	C: {
		"chisato_yamada__suite_nihonkai": {
			lastfm_url: "https://www.last.fm/music/Chisato+Yamada/Suite+Nihonkai+%E7%B5%84%E6%9B%B2%E3%80%8C%E6%97%A5%E6%9C%AC%E6%B5%B7%E3%80%8D%E6%B4%A5%E8%BB%BD%E3%81%98%E3%82%87%E3%82%93%E3%81%8B%E3%82%89%E6%B5%81%E3%82%8C%E7%AF%80",
			rym_url: "https://rateyourmusic.com/release/album/%E5%B1%B1%E7%94%B0%E5%8D%83%E9%87%8C/suite_nihonkai_%E7%B5%84%E6%9B%B2%E3%80%8C%E6%97%A5%E6%9C%AC%E6%B5%B7%E3%80%8D%E6%B4%A5%E8%BB%BD%E3%81%98%E3%82%87%E3%82%93%E3%81%8B%E3%82%89%E6%B5%81%E3%82%8C%E7%AF%80/",
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/8d6f20e4ef9693e3c33f29ea141d591c.jpg#8d6f20e4ef9693e3c33f29ea141d591c",
			youtube_url: "https://www.youtube.com/watch?v=VUyMjI356kw&t=3s&pp=ygUeY2hpc2F0b195YW1hZGFfX3N1aXRlX25paG9ua2Fp",
			artist_name_Japanese: "山田千里",
			year_of_release: "1981",
			genres: ["Tsugaru shamisen; Min'yō Music; J-acoustic; J-funk; Funk"],
			my_rating: 9.5,
			year_of_discovery: "2021",
			my_review: ReactDomServer.renderToString(ChisatoYamadaReview()),
		},

		"cavern_of_anti_matter__in_fabric_ost": {
			lastfm_url: "https://www.last.fm/music/Cavern+of+Anti-Matter/In+Fabric+OST",
			rym_url: "https://rateyourmusic.com/release/album/cavern-of-anti-matter/in-fabric-ost/",
			spotify_url: "https://open.spotify.com/album/56h30DA2RokyYVDobT2U5a?si=aLA2-KZuQAqetrxduGaClw",
			year_of_release: "2020",
			year_of_discovery: "2023",
			genres: ["Film soundtrack; Horror synth; Synthwave; Electronic"],
			my_rating: 8.0,
			my_review: "",
		},
	
		"charli_xcx__how_im_feeling_now": {
			lastfm_url: "https://www.last.fm/music/Charli+XCX/how+i%27m+feeling+now",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2020",
			year_of_discovery: "2020",
			genres: ["Hyperpop; Pop; Dance pop; Electropop; Alternative pop; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"clown_core__van": {
			lastfm_url: "https://www.last.fm/music/Clown+Core/Van",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1996",
			year_of_discovery: "2023",
			genres: ["Avant-garde metal; Experimental rock; Jazz; Jazz fusion; Noise; Breakbeat; Grindcore; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"crumb__locket": {
			lastfm_url: "https://www.last.fm/music/Crumb/Locket",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/4pKJ14jcQKqko0cVBYoeWR?si=bDMB7rMHTiqoDERIvxyFkA",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["Indie pop; Dream pop"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"c418__minecraft_volume_alpha": {
			lastfm_url: "https://www.last.fm/music/C418/Minecraft+Volume+Alpha",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3Gt7rOjcZQoHCfnKl5AkK7?si=ouGhtOopT6iRPCEEoz7oKw",
			year_of_release: "2011",
			year_of_discovery: "2011",
			genres: ["Ambient; Piano"],
			my_rating: 9.0,
			my_review: "",
		},

		"crumb__jinx": {
			lastfm_url: "https://www.last.fm/music/Crumb/Jinx",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2019",
			year_of_discovery: "2019",
			genres: ["Psychdelic pop; Dream pop; Indie pop; Indie rock"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	D: {
		"daft_punk__discovery": {
			lastfm_url: "https://www.last.fm/music/Daft+Punk/Discovery",
			rym_url: "https://rateyourmusic.com/release/album/daft-punk/discovery/",
			spotify_url: "https://open.spotify.com/album/2noRn2Aes5aoNVsU6iWThc?si=QujuPptJTxSzF6-S9tqQsw",
			year_of_release: "2001",
			genres: ["French House; Electro-Disco; Funky House; Dance pop; Synth Funk; Nu-disco; Electronic"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/54010ae7c4fa4c96a1e1872a051d9ecc.jpg#54010ae7c4fa4c96a1e1872a051d9ecc",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2020",
		},

		"dead_can_dance__within_the_realm_of_a_dying_sun": {
			lastfm_url: "https://www.last.fm/music/Dead+Can+Dance/Within+the+Realm+of+a+Dying+Sun",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/4WGpRBfDu7OJ4Rimkzu9jp?si=WIUEm_yvQrmBcYM3D1QhwQ",
			year_of_release: "1987",
			year_of_discovery: "2022",
			genres: ["Neo-classical darkwave; Gothic rock; Ambient; Neo-classical"],
			themes: ["Atmospheric"],
			my_rating: 9.5,
			my_review: "",
		},

		"dominique_quiot__l_univers_de_la_mer": {
			lastfm_url: "https://www.last.fm/music/Dominique+Guiot/L%27univers+De+La+Mer",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1978",
			year_of_discovery: "2020",
			genres: ["Downtempo; Ambient; Synthpop; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"daniel_hart__a_ghost_story_soundtrack": {
			lastfm_url: "https://www.last.fm/music/Daniel+Hart/A+Ghost+Story",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2021",
			genres: ["Film soundtrack; Ambient; Post-minimalism; Modern classical"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"dirty_projectors__mount_wittenburg_orca": {
			lastfm_url: "https://www.last.fm/music/Dirty+Projectors+%252B+Bj%C3%B6rk/Mount+Wittenberg+Orca",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2010",
			year_of_discovery: "2022",
			genres: ["Alternative pop; Experimental pop; Progressive pop; Downtempo; Vocal"],
			my_rating: 9.0,
			my_review: "",
		},

		"daft_punk__random_access_memories": {
			lastfm_url: "https://www.last.fm/music/Daft+Punk/Random+Access+Memories",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2013",
			year_of_discovery: "2018",
			genres: ["Disco; French house; Progressive pop; Electropop; Synthpop; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"daniel_caesar__freudian": {
			lastfm_url: "https://www.last.fm/music/Daniel+Caesar/Freudian",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["R&B; Neo-soul; Gospel music"],
			my_rating: 9.0,
			my_review: "",
		},

		"digable_planets__reachin_a_new_refutiation_of_time_and_space": {
			lastfm_url: "https://www.last.fm/music/Digable+Planets/Reachin%E2%80%99+(A+New+Refutation+of+Time+and+Space)",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1993",
			year_of_discovery: "2021",
			genres: ["Hip-Hop; Rap; Jazz rap; Alternative Hip-hop"],
			themes: ["Chill", "Conscious lyricism"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	E: {
		"elliott_smith__figure_8": {
			lastfm_url: "https://www.last.fm/music/Elliott+Smith/Figure+8",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7DC0pE943VR5tAKIvQXHts?si=SxI5tb5qTGeu_UOlhxJMJw",
			year_of_release: "2000",
			year_of_discovery: "2021",
			genres: ["Indie rock; Chamber pop; Indie folk; Singer-songwritter"],
			my_rating: 9.5,
			my_review: "",
		},

		"erik_satie__3_gymnopedies": {
			lastfm_url: "https://www.last.fm/music/Erik+Satie/Satie:+3+Gymnop%C3%A9dies;+6+Gnossiennes+etc.",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7IjGFO75lb5ZP9ACSIjEAr?si=PllvZt7ITrqk5ohcZLVYOg",
			year_of_release: "1984",
			year_of_discovery: "2022",
			genres: ["Piano; Modern classical"],
			my_rating: 9.0,
			my_review: "",
		},

		"enter_shikari__the_mindsweep": {
			lastfm_url: "https://www.last.fm/music/Enter+Shikari/The+Mindsweep",
			rym_url: "https://rateyourmusic.com/release/album/enter-shikari/the-mindsweep/",
			spotify_url: "https://open.spotify.com/album/3q8PS1Zkx3a0Zo6Ld2L1d7?si=fXyeTBifQii8VHcNqrMEeQ",
			year_of_release: "2015",
			genres: ["Post-hardcore; Drum and bass; Metalcore; Trancecore; Trance; Electronicore"],
			custom_cover_url: "https://www.nme.com/wp-content/uploads/2016/09/2014EnterShikari_TheMindSweep_081014.jpg",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2016",
		},

		"enter_shikari__take_to_the_skies": {
			lastfm_url: "https://www.last.fm/music/Enter+Shikari/Take+to+the+Skies",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/5cO7wtkaJCY3SiV6g0MKHE?si=ozcYAQg_S5-q7SwrvapM2w",
			year_of_release: "2007",
			year_of_discovery: "2015",
			genres: ["Post-hardcore; Metalcore; Alternative rock; Drum and bass; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"enter_shikari__common_dreads": {
			lastfm_url: "https://www.last.fm/music/Enter+Shikari/Common+Dreads",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2009",
			year_of_discovery: "2015",
			genres: ["Post-hardcore; Alternative rock; Metalcore; Electronicore"],
			my_rating: 8.5,
			my_review: "",
		},

		"enter_shikari__a_flash_flood_of_colour": {
			lastfm_url: "https://www.last.fm/music/Enter+Shikari/A+Flash+Flood+of+Colour",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2014",
			year_of_discovery: "2014",
			genres: ["Metalcore; Post-hardcore; Alternative rock; Trancecore; Electronic"],
			themes: ["Rave", "Political"],
			my_rating: 9.0,
			my_review: "",
		},

		"emily_scott_robinson__travelling_mercies": {
			lastfm_url: "https://www.last.fm/music/Emily+Scott+Robinson/Traveling+Mercies",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2019",
			year_of_discovery: "2021",
			genres: ["Country; Americana; Folk; Bluegrass"],
			my_rating: 9.0,
			my_review: "",
		},

		"eberhard_weber__fluid_rustle": {
			lastfm_url: "https://www.last.fm/music/Eberhard+Weber/Fluid+Rustle",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1979",
			year_of_discovery: "2023",
			genres: ["Jazz; ECM style jazz; Chamber jazz; Ambient; Minimalism; Norwegian jazz"],
			themes: ["Norwegian"],
			my_rating: 8.5,
			my_review: "",
		},

		"eberhard_weber__colors_of_chloe": {
			lastfm_url: "https://www.last.fm/music/Eberhard+Weber/The+Colours+Of+Chlo%C3%AB",
			rym_url: "https://rateyourmusic.com/release/album/eberhard-weber/the-colours-of-chloe/",
			spotify_url: "https://open.spotify.com/album/6q8vN3Qdyxk6o1fGpY64qz?si=LZdH29UcSfmCNejpkvrbKA",
			year_of_release: "1974",
			year_of_discovery: "2023",
			genres: ["ECM style jazz; Chamber jazz; Jazz fusion; Minimalism; Third stream; Jazz; Norwegian jazz"],
			themes: ["Norwegian"],
			my_rating: 8.0,
			my_review: "",
		},
	},

	F: {
		"four_tet__new_energy": {
			lastfm_url: "https://www.last.fm/music/Four+Tet/New+Energy",
			rym_url: "https://rateyourmusic.com/release/album/four-tet/new-energy/",
			spotify_url: "https://open.spotify.com/album/74r6JJ97ipO0CREXP9PMqZ?si=87jNGD_VTUyt1ppVDritsw",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["IDM; Microhouse; Downtempo; Ambient house; Folktronica; Electronic"],
			my_rating: 8.0,
			my_review: "",
		},

		"fleet_foxes__fleet_foxes": {
			lastfm_url: "https://www.last.fm/music/Fleet+Foxes/Fleet+Foxes",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/1rfgmU0AYNwWfS88pCOlX7?si=bTDwgxmiTYWIEMqny7Dz0Q",
			year_of_release: "2008",
			year_of_discovery: "2017",
			genres: ["Indie folk; Indie pop; Chamber pop; Folk pop; Baroque pop; Folk rock"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"fiona_apple__the_idler_wheel": {
			lastfm_url: "https://www.last.fm/music/Fiona+Apple/The+Idler+Wheel+Is+Wiser+Than+the+Driver+of+the+Screw+and+Whipping+Cords+Will+Serve+You+More+Than+Ropes+Will+Ever+Do",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/6B5favhKTShFTjRLsKIUfa?si=KFeS6RYVSqS65hDTY2fhTg",
			year_of_release: "2012",
			year_of_discovery: "2021",
			genres: ["Indie rock; Alternative folk"],
			my_rating: 9.5,
			my_review: "",
		},

		"frank_ocean__blonde": {
			lastfm_url: "https://www.last.fm/music/Frank+Ocean/Blonde",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2017",
			genres: ["R&B; Neo-soul; Hip-Hop; Rap"],
			my_rating: 9.0,
			my_review: "",
		},

		"fleet_foxes__helplessness_blues": {
			lastfm_url: "https://www.last.fm/music/Fleet+Foxes/Helplessness+Blues",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2011",
			year_of_discovery: "2018",
			genres: ["Indie folk; Folk; Folk pop; Chamber folk; Baroque pop"],
			my_rating: 9.0,
			my_review: "",
		},	

		"father_john_misty__pure_comedy": {
			lastfm_url: "https://www.last.fm/music/Father+John+Misty/Pure+Comedy",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2023",
			genres: ["Folk; Indie folk; Baroque pop; Baroque folk; Singer-songwritter"],
			themes: ["Contemplative", "Existential", "Peaceful"],
			my_rating: 9.0,
			my_review: "",
		},

		"fightstar__one_day_son_this_will_all_be_yours": {
			lastfm_url: "https://www.last.fm/music/Fightstar/One+Day+Son,+This+Will+All+Be+Yours",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["Post-hardcore; Emo; Screamo; Alternative rock"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	G: {
		"guy_farley__cashback_ost": {
			lastfm_url: "https://www.last.fm/music/Guy+Farley/Cashback",
			rym_url: "https://rateyourmusic.com/release/album/guy_farley/cashback/",
			spotify_url: "https://open.spotify.com/album/03rRA3Uy2reDpkpTcCgkoO?si=tV027r1kTTKLL5eYZMh7Lg",
			year_of_release: "2008",
			year_of_discovery: "2023",
			genres: ["Film soundtrack; Modern classical"],
			my_rating: 8.0,
			my_review: "",
		},

		"grant_kirkhope__banjo_kazooie": {
			lastfm_url: "https://www.last.fm/music/Grant+Kirkhope/Banjo-Kazooie",
			rym_url: "",
			youtube_url: "https://www.youtube.com/watch?v=wcD3aQaCTd0&t=99s&pp=ygUYYmFuam8ga2F6b29pZSBzb3VuZHRyYWNr",
			year_of_release: "1998",
			year_of_discovery: "2023",
			genres: ["Video game soundtrack; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"g_jones__acid_disk_2": {
			lastfm_url: "https://www.last.fm/music/G+Jones/Acid+Disk+2",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1978",
			year_of_discovery: "2013",
			genres: ["Acid house; Hybrid trap; Trap [EDM]; Future bass; Breakbeat; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"g_jones__illusory_tracks": {
			lastfm_url: "https://www.last.fm/music/G+Jones/Illusory+Tracks",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Breakbeat; Hybrid trap; Drum and bass; Acid breaks; Downtempo; Electronic"],
			my_rating: 8.5,
			my_review: "",
		},

		"grimes__art_angels": {
			lastfm_url: "https://www.last.fm/music/Grimes/Art+Angels",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2015",
			year_of_discovery: "2020",
			genres: ["Pop; Synthpop; Indie pop; Dance pop; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	H: {
		"hakushi_hasegawa__somoku_hodo": {
			lastfm_url: "https://www.last.fm/music/hakushi+hasegawa/Somoku+Hodo",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3RRuuRZr2mQT0WoyNHNoBd?si=IULOKUyNTK-_QvRSxgvErA",
			year_of_release: "2018",
			year_of_discovery: "2023",
			genres: ["Jazz; Nu jazz; J-pop; Vocaloid; Breakbeat; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

			
		"hiromi_alive": {
			lastfm_url: "https://www.last.fm/music/Hiromi/Alive",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/18L36uUa7xLegzjkvr10ev?si=1Ew_DKL6QgmX5DCr3Z6D9g",
			year_of_release: "2014",
			year_of_discovery: "2023",
			genres: ["Jazz; Jazz fusion; Post-bop"],
			my_rating: 9.5,
			my_review: "",
		},

		"hiromi__silver_lining_suite": {
			lastfm_url: "https://www.last.fm/music/Hiromi/Silver+Lining+Suite",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2021",
			year_of_discovery: "2023",
			genres: ["Jazz; Jazz fusion; Third stream jazz"],
			my_rating: 9.0,
			my_review: "",
		},

		"hiromi__time_control": {
			lastfm_url: "https://www.last.fm/music/Hiromi/Time+Control",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2007",
			year_of_discovery: "2023",
			genres: ["Jazz fusion; Progressive rock; Jazz; Jazz funk; Funk"],
			my_rating: 8.5,
			my_review: "",
		},

		"hiromi__spark": {
			lastfm_url: "https://www.last.fm/music/Hiromi/Spark",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2023",
			genres: ["Jazz fusion; Jazz; Post-Bop"],
			my_rating: 8.5,
			my_review: "",
		},

	},

	I: {
		"igorrr__savage_sinusoid": {
			lastfm_url: "https://www.last.fm/music/Igorrr/Savage+Sinusoid",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2NsGk9oBBBMfblYdLcjYhu?si=dBE06x5bRD2yxWihazG-Dw",
			year_of_release: "2017",
			year_of_discovery: "2021",
			genres: ["Breakcore; Avant-garde metal; Balkan; Electronic"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"ichiko_aoba__windswept_adan": {
			lastfm_url: "https://www.last.fm/music/Ichiko+Aoba/Windswept+Adan",
			rym_url: "https://rateyourmusic.com/release/album/%E9%9D%92%E8%91%89%E5%B8%82%E5%AD%90/%E3%82%A2%E3%83%80%E3%83%B3%E3%81%AE%E9%A2%A8-windswept-adan/",
			spotify_url: "https://open.spotify.com/album/0LxeUCxtPfUtnHTKbW52MB?si=rupRpQnBTSyKndTJrbuDUA",
			year_of_release: "2020",
			year_of_discovery: "2021",
			artist_name_Japanese: "青葉市子",
			genres: ["J-folk; Chamber folk; Ambient; New age; Nature recordings; J-acoustic"],
			themes: ["Japanese", "Majestic", "Atmospheric"],
			custom_cover_url: "https://m.media-amazon.com/images/I/71Q93PPdn0L._UF894,1000_QL80_.jpg",
			my_rating: 10,
			my_review: "",
		},
	
		"iglooghost__steel_mogu": {
			lastfm_url: "https://www.last.fm/music/Iglooghost/Steel+Mogu",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/0D50foA8oPustAg1Z8cqjF?si=w9j3hEzxQFCB_W1xNFASiQ",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["Future bass; Wonky; Glitch; Future garage; Footwork; Breakbeat; Nu jazz; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"iglooghost__neo_wax_bloom": {
			lastfm_url: "https://www.last.fm/music/Iglooghost/Ne%C5%8D+Wax+Bloom",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["Future bass; Wonky; Glitch; Future garage; Footwork; Breakbeat; Nu jazz; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"ichiko_aoba__qp": {
			lastfm_url: "https://www.last.fm/music/Ichiko+Aoba/qp",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2018",
			year_of_discovery: "2021",
			genres: ["J-folk; J-acoustic; Folk"],
			themes: ["Japanese"],
			my_rating: 8.0,
			my_review: "",
		},
		
		"issues__issues": {
			lastfm_url: "https://www.last.fm/music/Issues/Issues",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2014",
			year_of_discovery: "2015",
			genres: ["Nu metal; Metalcore; Post-hardcore; Electronicore"],
			my_rating: 8.5,
			my_review: "",
		},

		"iglooghost__clear_tamei": {
			lastfm_url: "https://www.last.fm/music/Iglooghost/Clear+Tamei",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2008",
			year_of_discovery: "2021",
			genres: ["Future bass; Wonky; Glitch; Future garage; Footwork; Breakbeat; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"issues__black_diamonds": {
			lastfm_url: "https://www.last.fm/music/Issues/Black+Diamonds",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2012",
			year_of_discovery: "2023",
			genres: ["Nu metal; Alternative metal"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	J: {
		"joe_hisaishi__kid_return_ost": {
			lastfm_url: "https://www.last.fm/music/Joe+Hisaishi/Kids+Return+(%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%83%BB%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF)",
			rym_url: "https://rateyourmusic.com/release/album/%E4%B9%85%E7%9F%B3%E8%AD%B2/kids_return/",
			spotify_url: "https://open.spotify.com/album/32TaUR88QyqMkXT4h7ffm0?si=OSTF7MkaSriZfrGzvFcj6g",
			year_of_release: "1996",
			year_of_discovery: "2024",
			artist_name_English: "Joe Hisaishi",
			genres: ["Film soundtrack; Neoclassical New Age; New age; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"joe_hisaishi__the_wind_rises": {
			lastfm_url: "https://www.last.fm/music/%E4%B9%85%E7%9F%B3%E8%AD%B2/The+Wind+Rises+Soundtrack",
			rym_url: "https://rateyourmusic.com/release/album/%E4%B9%85%E7%9F%B3%E8%AD%B2/%E9%A2%A8%E7%AB%8B%E3%81%A1%E3%81%AC_%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF__kaze_tachinu_soundtrack_/",
			spotify_url: "https://open.spotify.com/album/59U5FQ4kDEt11Q2UcFu1dK?si=nA7B5VZLTYe8Y9Q-ul-yxg",
			year_of_release: "2013",
			year_of_discovery: "2022",
			artist_name_English: "Joe Hisaishi",
			genres: ["Film soundtrack"],
			my_rating: 9.0,
			custom_cover_url: "https://i.scdn.co/image/ab67616d0000b273c853c5a8535cc3dc394efc58",
			my_review: "",
		},
	
		"jon_hopkins__contact_note": {
			lastfm_url: "https://www.last.fm/music/Jon+Hopkins/Contact+Note",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/582EKMkWdR5wmroAm9NqfE?si=6noo_W6rTc2FRp44leu-pg",
			year_of_release: "2004",
			year_of_discovery: "2017",
			genres: ["Ambient; Downtempo; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"joyce_moreno__natureza": {
			lastfm_url: "https://www.last.fm/music/Joyce+Moreno/Natureza",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1980",
			year_of_discovery: "2022",
			genres: ["Jazz; Bossa nova; MPB; Latin jazz"],
			themes: ["Brazilian"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"joe_hisaishi__a_symphonic_celebration": {
			lastfm_url: "https://www.last.fm/music/%E4%B9%85%E7%9F%B3%E8%AD%B2/A+Symphonic+Celebration+(Music+from+the+Studio+Ghibli+Films+of+Hayao+Miyazaki)",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2023",
			year_of_discovery: "2023",
			genres: ["Film soundtrack; Modern classical"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"joe_hisaishi__kikis_delivery_service": {
			lastfm_url: "https://www.last.fm/music/%E4%B9%85%E7%9F%B3%E8%AD%B2/Kiki%27s+Delivery+Service+Soundtrack+Music+Collection",
			rym_url: "https://rateyourmusic.com/release/album/%E4%B9%85%E7%9F%B3%E8%AD%B2/kikis-delivery-service-original-soundtrack/",
			spotify_url: "https://open.spotify.com/album/2NO5lYWs4aWpsmHOjF4JHk?si=eitK7DgpTYWtnaV3aQ0E6g",
			year_of_release: "1989",
			year_of_discovery: "2022",
			artist_name_English: "Joe Hisaishi",
			genres: ["Film soundtrack; Anime soundtrack; Japanese anime soundtrack"],
			my_rating: 9.5,
			my_review: "",
		},

		"jon_brion__synecdoche_new_york": {
			lastfm_url: "https://www.last.fm/music/Jon+Brion/Synecdoche,+New+York",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2008",
			year_of_discovery: "2020",
			genres: ["Film soundtrack; Jazz pop"],
			my_rating: 9.0,
			my_review: "",
		},

		"jme__integrity": {
			lastfm_url: "https://www.last.fm/music/JME/Integrity",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2015",
			year_of_discovery: "2015",
			genres: ["Grime; UK Rap; Hip-Hop; Rap"],
			my_rating: 8.5,
			my_review: "",
		},
	},

	K: {
		"kendrick_lamar__section_80": {
			lastfm_url: "https://www.last.fm/music/Kendrick+Lamar/Section.80",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/1bkN9nIkkCnXeG4yitVS1J?si=JDTcdWdDRHuUaI-8amHgIw",
			year_of_release: "2011",
			year_of_discovery: "2016",
			genres: ["Hip-Hop; Rap"],
			my_rating: 9.5,
			my_review: "",
		},
		
		"kendrick_lamar__to_pimp_a_butterfly": {
			lastfm_url: "https://www.last.fm/music/Kendrick+Lamar/To+Pimp+a+Butterfly",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7ycBtnsMtyVbbwTfJwRjSP?si=AEpJhbLTShq-Qg1vAUlvSQ",
			year_of_release: "2015",
			year_of_discovery: "2016",
			genres: ["Hip-Hop; Rap; Jazz rap; Jazz; Funk"],
			my_rating: 9.5,
			my_review: "",
		},
		
		"kendrick_lamar__untitled_unmastered": {
			lastfm_url: "https://www.last.fm/music/Kendrick+Lamar/Untitled+Unmastered",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/0kL3TYRsSXnu0iJvFO3rud?si=DhXStEWJRJK1NZnRIwJovQ",
			year_of_release: "2016",
			year_of_discovery: "2016",
			genres: ["Hip-Hop; Rap; Funk; Jazz rap"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"kero_kero_bonito__time_and_place": {
			lastfm_url: "https://www.last.fm/music/Kero+Kero+Bonito/Time+%27n%27+Place",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2018",
			year_of_discovery: "2019",
			genres: ["Noise pop; Synthpop; Indie rock; Dream pop; Progressive pop; Shoegaze; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"king_gizzard_and_the_lizard_wizard__nonagon_infinity": {
			lastfm_url: "https://www.last.fm/music/King+Gizzard+&+The+Lizard+Wizard/Nonagon+Infinity",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2018",
			genres: ["Psychedlic rock; Australian psychedlic rock"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"katzenjammer__le_pop": {
			lastfm_url: "https://www.last.fm/music/Katzenjammer/Le+Pop",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2008",
			year_of_discovery: "2021",
			genres: ["Klezmer; Alternative rock; Punk rock"],
			themes: ["Norwegian"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"klute__no_ones_listening_anymore": {
			lastfm_url: "https://www.last.fm/music/Klute/No+One%27s+Listening+Anymore",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2004",
			year_of_discovery: "2021",
			genres: ["Drum and bass; Breakbeat; Industrial; Downtempo; Techno; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"kendrick_lamar__good_kid_maad_city": {
			lastfm_url: "https://www.last.fm/music/Kendrick+Lamar/good+kid,+m.A.A.d+city+(Deluxe)",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2012",
			year_of_discovery: "2016",
			genres: ["Hip-Hop; Rap; Gangsta rap"],
			my_rating: 9.0,
			my_review: "",
		},

		"king_gizzard_and_the_lizard_wizard__paper_mache_dream_balloon": {
			lastfm_url: "https://www.last.fm/music/King+Gizzard+&+The+Lizard+Wizard/Paper+M%C3%A2ch%C3%A9+Dream+Balloon",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2015",
			year_of_discovery: "2018",
			genres: ["Psychedelic folk; Psychdelic pop; Dream pop; Folk rock; Folk"],
			my_rating: 9.0,
			my_review: "",
		},

		"king_gizzard_and_the_lizard_wizard__sketches_of_brunswick_east": {
			lastfm_url: "https://www.last.fm/music/King+Gizzard+&+The+Lizard+Wizard/Sketches+of+Brunswick+East",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2018",
			genres: ["Neo-Psychedelia; Psychedelic Pop; Australian psych"],
			my_rating: 8.5,
			my_review: "",
		},

		"kero_kero_bonito__intro_bonito": {
			lastfm_url: "https://www.last.fm/music/Kero+Kero+Bonito/Intro+Bonito",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2013",
			year_of_discovery: "2022",
			genres: ["Dance pop; Pop; Glitch pop; Hip-Hop"],
			my_rating: 8.5,
			my_review: "",
		},
		
		"kate_bush__never_for_ever": {
			lastfm_url: "https://www.last.fm/music/Kate+Bush/Never+for+Ever",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1980",
			year_of_discovery: "2020",
			genres: ["Progressive pop; Baroque pop; Art rock; Pop"],
			my_rating: 9.0,
			my_review: "",
		},

		"klaus_schulze__deus_arrakis": {
			lastfm_url: "https://www.last.fm/music/Klaus+Schulze/Deus+Arrakis",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Space ambient; Ambient; Electronic"],
			themes: ["Cosmic", "Vast", "Mysterious", "Atmospheric"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	L: {
		"laurent_perez_del_mar__the_red_turtle_soundtrack": {
			lastfm_url: "https://www.last.fm/music/Laurent+Perez+Del+Mar/The+Red+Turtle+(Original+Motion+Picture+Soundtrack)",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2021",
			genres: ["Film soundtrack; Ambient; Modern classical"],
			my_rating: 9.0,
			my_review: "",
		},

		"lone__galaxy_garden": {
			lastfm_url: "https://www.last.fm/music/Lone/Galaxy+Garden",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2012",
			year_of_discovery: "2022",
			genres: ["House; Breakbeat; IDM; Hardcore breaks; Footwork; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"lucrecia_dalt__syzygy": {
			lastfm_url: "https://www.last.fm/music/Lucrecia+Dalt/Syzygy",
			rym_url: "",
			youtube_url: "",
			year_of_release: "2013",
			year_of_discovery: "2020",
			genres: ["Ambient pop; Ambient; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"lily_allen__alright_still": {
			lastfm_url: "https://www.last.fm/music/Lily+Allen/Alright,+Still",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2006",
			year_of_discovery: "2009",
			genres: ["Pop; Reggae pop; Synthpop; R&B; Progressive pop"],
			my_rating: 9.0,
			my_review: "",
		},

		"lily_allen__its_not_me_its_you": {
			lastfm_url: "https://www.last.fm/music/Lily+Allen/It%27s+Not+Me,+It%27s+You",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2008",
			year_of_discovery: "2009",
			genres: ["Pop; Reggae pop; Synthpop; Indie pop"],
			my_rating: 9.0,
			my_review: "",
		},

		"linkin_park__hybrid_theory": {
			lastfm_url: "https://www.last.fm/music/Linkin+Park/Hybrid+Theory",
			rym_url: "https://rateyourmusic.com/release/album/linkin-park/hybrid-theory/",
			spotify_url: "https://open.spotify.com/album/6PFPjumGRpZnBzqnDci6qJ?si=zgoR-iP-TrS-WshQFRO52g",
			year_of_release: "2000",
			year_of_discovery: "2016",
			genres: ["Nu metal; Alternative rock; Industrial rock; Electronic"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/cc15ebc58ec625979776cabaaaa282fa.jpg#cc15ebc58ec625979776cabaaaa282fa",
			my_rating: 10,
			my_review: "",
		},
	
		"linkin_park__a_thousand_suns": {
			lastfm_url: "https://www.last.fm/music/Linkin+Park/A+Thousand+Suns",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/5uvXx5ZQswNRFCdHR521YZ?si=DX7biNE7SzW-57oaQn7Usw",
			year_of_release: "2010",
			year_of_discovery: "2015",
			genres: ["Nu metal; Alternative rock; Industrial rock; Electronic"],
			my_rating: 10,
			my_review: "",
		},
		
		"linkin_park__meteora": {
			lastfm_url: "https://www.last.fm/music/Linkin+Park/Meteora",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/4Gfnly5CzMJQqkUFfoHaP3?si=5FSCLHt0SziWK1hDuTZ1hg",
			year_of_release: "2003",
			year_of_discovery: "2015",
			genres: ["Nu metal; Alternative metal; Alternative rock"],
			my_rating: 9.0,
			my_review: "",
		},

		"logic__young_sinatra_undeniable": {
			lastfm_url: "https://www.last.fm/music/Logic/Young+Sinatra:+Undeniable",
			rym_url: "",
			youtube_url: "https://youtube.com/playlist?list=PL9y_aRAKmsdtBN4Bag8rFx2Dqait6skY6&si=ohQN6hptx1Gn6HKG",
			year_of_release: "2012",
			year_of_discovery: "2015",
			genres: ["Hip-Hop; Rap; Pop rap"],
			my_rating: 9.0,
			my_review: "",
		},

		"logic__under_pressure": {
			lastfm_url: "https://www.last.fm/music/Logic/Under+Pressure+(Deluxe)",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/1Mk7Lei0Ra3hawezqmad5V?si=7buq1FOVQ8KZFOpLIf8ZzQ",
			year_of_release: "2014",
			year_of_discovery: "2016",
			genres: ["Hip-Hop; Rap; Pop rap"],
			my_rating: 9.5,
			my_review: "",
		},
	},

	M: {
		"metamatics__mind_mushing_git": {
			lastfm_url: "https://www.last.fm/music/Metamatics/Mind+Mushing+Git",
			rym_url: "https://rateyourmusic.com/release/album/metamatics/mind_mushing_git/",
			spotify_url: "https://open.spotify.com/album/2s1XgcAEXuBkKqEgVX5C4F?si=mhaG0H3uQESS9NZOvno0cA",
			year_of_release: "2003",
			genres: ["Electronic; Ambient; IDM; Ambient techno"],
			my_rating: 8.0,
			my_review: "",
			year_of_discovery: "2023",
		},

		"minseo__the_diary_of_youth": {
			lastfm_url: "https://www.last.fm/music/Minseo/The+Diary+of+Youth",
			rym_url: "https://rateyourmusic.com/release/ep/minseo/the-diary-of-youth/",
			spotify_url: "https://open.spotify.com/album/1OvlJHuqvSO9zVBLKATEu7?si=jh9b-gPPTqqbEyLslgtq9w",
			year_of_release: "2019",
			genres: ["K-pop; Jazz; Jazz pop"],
			my_rating: 8.0,
			my_review: "",
			year_of_discovery: "2023",
		},
	
		"marika_hackman__that_iron_taste": {
			lastfm_url: "https://www.last.fm/music/Marika+Hackman/That+Iron+Taste",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/1HBTigeKszgy2KJPna3hND?si=NeIcr6-hRRqYCLsqdBOZgw",
			year_of_release: "2013",
			year_of_discovery: "2013",
			genres: ["Folk; Indie folk; Singer-songwritter"],
			my_rating: 10,
			my_review: "",
		},
	
		"marika_hackman__we_slept_at_last": {
			lastfm_url: "https://www.last.fm/music/Marika+Hackman/We+Slept+at+Last",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7bGKJT7GMChX7lM3txM9Iz?si=lvnieLUxRSK-48MGk3BwdQ",
			year_of_release: "2015",
			year_of_discovery: "2016",
			genres: ["Indie folk; Alternative folk"],
			my_rating: 9.5,
			my_review: "",
		},
		
		"massive_attack__mezzanine": {
			lastfm_url: "https://www.last.fm/music/Massive+Attack/Mezzanine",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/49MNmJhZQewjt06rpwp6QR?si=QlLRBp5KRUeFLHpMyuuH9A",
			year_of_release: "1998",
			year_of_discovery: "2019",
			genres: ["Trip hop; Downtempo; Ambient pop; Alternative rock"],
			my_rating: 9.5,
			my_review: "",
		},
		
		"midroi__shinsekai": {
			lastfm_url: "https://www.last.fm/music/Midori/shinsekai",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2010",
			year_of_discovery: "2022",
			genres: ["J-rock; Jazz punk; Jazz fusion; Noise rock; J-pop; Punk"],
			my_rating: 9.0,
			my_review: "",
		},

		"moron_police__a_boat_on_the_sea": {
			lastfm_url: "https://www.last.fm/music/Moron+Police/A+Boat+on+the+Sea",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2ojezjS6Dw8MuSaI9OoOv7?si=XpQfQOG-QxOWismHTwvEtQ",
			year_of_release: "2019",
			year_of_discovery: "2021",
			genres: ["Progressive rock; Symphonic rock; Pop rock"],
			my_rating: 9.5,
			my_review: "",
		},
	
			
		"marika_hackman__deaf_heat": {
			lastfm_url: "https://www.last.fm/music/Marika+Hackman/Deaf+Heat+EP",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2NJInBQPfkmgWkNsx2m0DC?si=JKGSvqH0TcK0QaueDwOCcg",
			year_of_release: "2014",
			year_of_discovery: "2015",
			genres: ["Folk; Indie folk"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"machine_girl__wlfgrl": {
			lastfm_url: "https://www.last.fm/music/Machine+Girl/WLFGRL",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/1GezMTE4OA4tikMDBQK5u3?si=fUAphrORTLi-z9p9Vc-87Q",
			year_of_release: "2000",
			year_of_discovery: "2022",
			genres: ["Digital hardcore; Drum and bass; Footwork; Industrial; Breakbeat; Jungle; Hardcore breaks; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"midori__aratamemashite_hajimemashite_midori_desu": {
			lastfm_url: "https://www.last.fm/music/Midori/Aratamemashite+Hajimemashite+Midori+Desu",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2003",
			year_of_discovery: "2019",
			genres: ["J-rock; Jazz punk; Jazz fusion; Noise rock; J-pop; Punk;"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"maximum_the_hormone__yoshu_fukushu": {
			lastfm_url: "https://www.last.fm/music/Maximum+the+Hormone/Yoshu+Fukushu",
			rym_url: "https://rateyourmusic.com/release/album/%E3%83%9E%E3%82%AD%E3%82%B7%E3%83%9E%E3%83%A0-%E3%82%B6-%E3%83%9B%E3%83%AB%E3%83%A2%E3%83%B3/%E4%BA%88%E8%A5%B2%E5%BE%A9%E8%AE%90-yoshu-fukushu/",
			spotify_url: "https://open.spotify.com/album/5hQ7cw4d3lnUu8LRFLeOwf",
			year_of_release: "2013",
			year_of_discovery: "2024",
			genres: ["Alternative metal; Japanese hardcore; J-rock; Pop punk; Metalcore"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"mohini_dey__mohini_dey": {
			lastfm_url: "https://www.last.fm/music/Mohini+Dey/Mohini+Dey",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2023",
			year_of_discovery: "2023",
			genres: ["Jazz fusion; Jazz; Djent; Progressive metal; Funk; Funk metal"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"misun__superstitions": {
			lastfm_url: "https://www.last.fm/music/MISUN/Superstitions",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2014",
			year_of_discovery: "2015",
			genres: ["Pop; Dance pop; Indie pop; Synthpop"],
			themes: ["Summery"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"marika_hackman__sugar_blind": {
			lastfm_url: "https://www.last.fm/music/Marika+Hackman/Sugar+Blind+EP",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2013",
			year_of_discovery: "2014",
			genres: ["Folk; Indie folk; Chamber folk"],
			my_rating: 9.0,
			my_review: "",
		},

		"milt_jackson__bags_and_trane": {
			lastfm_url: "https://www.last.fm/music/Milt+Jackson+&+John+Coltrane/Bags+&+Trane",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1961",
			year_of_discovery: "2021",
			genres: ["Jazz; Post-bop"],
			themes: ["Vibraphone"],
			my_rating: 9.0,
			my_review: "",
		},

		"matmos__plastic_anniversary": {
			lastfm_url: "https://www.last.fm/music/Matmos/Plastic+Anniversary",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2019",
			year_of_discovery: "2019",
			genres: ["Minimal techno; Glitch; Experimental; Electronic"],
			themes: ["Plastic instruments", "Apocalyptic", "Organic"],
			my_rating: 9.0,
			my_review: "",
		},

		"mia__matangi": {
			lastfm_url: "https://www.last.fm/music/M.I.A./Matangi",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2013",
			year_of_discovery: "2021",
			genres: ["Dance pop; Indietronica; New rave; Hip hop; Electronic"],
			my_rating: 8.5,
			my_review: "",
		},

		"magdalena_bay__mercurial_world": {
			lastfm_url: "https://www.last.fm/music/Magdalena+Bay/Mercurial+World",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2021",
			year_of_discovery: "2021",
			genres: ["Art pop; Electropop; Synthpop; Electronic"],
			my_rating: 8.5,
			my_review: "",
		},

		"meridian_brothers__el_grupo_renacimiento": {
			lastfm_url: "https://www.last.fm/music/Meridian+Brothers/Meridian+Brothers+&+El+Grupo+Renacimiento",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Salsa; Latin afrobeat; Latin electronic; Latin funk; Musica tropicale; Tropicanibalismo; Tropicália"],
			themes: ["Colombia", "Latin rhythms"],
			my_rating: 8.5,
			my_review: "",
		},

		"mort_garson__plantasia": {
			lastfm_url: "https://www.last.fm/music/Mort+Garson/Plantasia",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1976",
			year_of_discovery: "2018",
			genres: ["Space age pop"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"mf_doom__mm_food": {
			lastfm_url: "https://www.last.fm/music/MF+DOOM/MM..FOOD",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2004",
			year_of_discovery: "2018",
			genres: ["Hip-Hop; Rap"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	N: {
		"nanoray__digimaiden": {
			lastfm_url: "https://www.last.fm/music/NANORAY/DIGIMAIDEN",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3HU9kKXZaaUK69KpAwZKvO?si=5VUcvS9UT8u1kiDODLFKMQ",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Breakbeat; Hardcore breaks; Electronic"],
			themes: ["Rave", "Intense"],
			my_rating: 9.5,
			my_review: "",
		},

		"nothing_but_thieves__broken_machine": {
			lastfm_url: "https://www.last.fm/music/Nothing+But+Thieves/Broken+Machine+(Deluxe)",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2017",
			genres: ["Alternative rock; Indie rock"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"nothing_but_thieves__nothing_but_thieves": {
			lastfm_url: "https://www.last.fm/music/Nothing+But+Thieves/Nothing+But+Thieves+(Deluxe)",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3q4BkDV5B7sczFcfrIl2a2?si=szGhGRH5R46M4feRo2oaSg",
			year_of_release: "2015",
			year_of_discovery: "2015",
			genres: ["Alternative rock; Indie rock"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"nas__illmatic": {
			lastfm_url: "https://www.last.fm/music/Nas/Illmatic",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3kEtdS2pH6hKcMU9Wioob1?si=M09PbYNTRRONyz1noGGSWw",
			year_of_release: "1994",
			year_of_discovery: "2018",
			genres: ["Hip-Hop; Rap; Gangsta rap"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"nine_inch_nails__the_fragile": {
			lastfm_url: "https://www.last.fm/music/Nine+Inch+Nails/The+Fragile",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/4uiVwLbTzE6VMkXpaDAwB8?si=qCgtd6dCRomwY-1KCyP8Qg",
			year_of_release: "1999",
			year_of_discovery: "2020",
			genres: ["Industrial; Industrial metal; Alternative rock; Nu metal"],
			my_rating: 9.5,
			my_review: "",
		},
		
		"nine_inch_nails__the_downward_spiral": {
			lastfm_url: "https://www.last.fm/music/Nine+Inch+Nails/The+Downward+Spiral+(Deluxe+Edition)",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7a7arAXDE0BiaMgHLhdjGF?si=jZ76RIHcQ2OmqHxQANKVSA",
			year_of_release: "1994",
			year_of_discovery: "2020",
			genres: ["Industrial; Industrial metal; Alternative rock; Nu metal"],
			my_rating: 9.5,
			my_review: "",
		},

		"namy__colorful": {
			lastfm_url: "https://www.last.fm/music/Namy/Colorful",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2011",
			year_of_discovery: "2021",
			genres: ["Jazz pop; Jazz; Pop; Downtempo; J-pop"],
			my_rating: 9.0,
			my_review: "",
		},

		"nick_drake__bryter_layer": {
			lastfm_url: "https://www.last.fm/music/Nick+Drake/Bryter+Layter",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1971",
			year_of_discovery: "2021",
			genres: ["Folk"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	O: {
		"ozric_tentacles__spirals_in_hyperspace": {
			lastfm_url: "https://www.last.fm/music/Ozric+Tentacles/Spirals+in+Hyperspace",
			rym_url: "https://rateyourmusic.com/release/album/ozric-tentacles/spirals-in-hyperspace/",
			spotify_url: "https://open.spotify.com/album/7EVKKZMWphUwkGzntYSnEz?si=zvEtf8KGS1u5zDJ9tPm42A",
			year_of_release: "2004",
			year_of_discovery: "2024",
			genres: ["Space Rock; Progressive rock; Jazz fusion; Psychedelic Rock; Livetronica"],
			my_rating: 9.0,
			my_review: "",
		},

		"orbital__octane_soundtrack": {
			lastfm_url: "https://www.last.fm/music/Orbital/Octane+Original+Soundtrack",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2003",
			year_of_discovery: "2019",
			genres: ["Film soundtrack; Ambient; Ambient techno"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"orbital__in_sides": {
			lastfm_url: "https://www.last.fm/music/Orbital/In+Sides",
			rym_url: "https://rateyourmusic.com/release/album/orbital/in-sides/",
			spotify_url: "https://open.spotify.com/album/1wXyzUmlgN6G1DXIY0Sh8l?si=Et6pXDkWSjqYiG1zSAPkuQ",
			year_of_release: "1997",
			genres: ["Ambient techno; IDM; Ambient; Breakbeat; Progressive Breaks; Electronic"],
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2017",
			custom_cover_url: "https://f4.bcbits.com/img/a1871008282_10.jpg",
		},
	
		
		"orbital__snivilization": {
			lastfm_url: "https://www.last.fm/music/Orbital/Snivilization",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2biXiNkJXdREKZwx4HrhZE?si=CTCPAaamQKiaePEZ6Ux3QQ",
			year_of_release: "1994",
			year_of_discovery: "2018",
			genres: ["Ambient techno; Techno; Ambient; Breakbeat; IDM; Electronic"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"orbital__the_middle_of_nowhere": {
			lastfm_url: "https://www.last.fm/music/Orbital/The+Middle+of+Nowhere",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/6xCIBKlELMK5cUSsjWJzG6?si=4qrTD0V5R56gGkx-hXXRNw",
			year_of_release: "1999",
			year_of_discovery: "2018",
			genres: ["Ambient techno; Techno; Ambient; Breakbeat; IDM; Electronic"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"oskar_schuster__sneeuwland": {
			lastfm_url: "https://www.last.fm/music/Oskar+Schuster/Sneeuwland",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3KecNg67vOvyn9lOcBAJYf?si=YWZkMTKuTA2arPyMupJ_oQ",
			year_of_release: "2014",
			year_of_discovery: "2015",
			genres: ["Modern classical; Piano"],
			my_rating: 9.0,
			my_review: "",
		},

		"open_mike_eagle__brick_body_kids_still_daydream": {
			lastfm_url: "https://www.last.fm/music/Open+Mike+Eagle/Brick+Body+Kids+Still+Daydream",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2019",
			genres: ["Hip-Hop; Rap"],
			my_rating: 9.0,
			my_review: "",
		},

		"opposite_day__opposite_day": {
			lastfm_url: "https://www.last.fm/music/Opposite+Day/What+is+is%3F",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2009",
			year_of_discovery: "2009",
			genres: ["Alternative rock"],
			my_rating: 8.5,
			my_review: "",
		},
		"oskar_schuster__matilda": {
			lastfm_url: "https://www.last.fm/music/Oskar+Schuster/Matilda",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2015",
			year_of_discovery: "2015",
			genres: ["Piano; Minimalism"],
			my_rating: 8.5,
			my_review: "",
		},
		"oskar_schuster__les_valses_invisibles": {
			lastfm_url: "https://www.last.fm/music/Oskar+Schuster/Les+Valses+Invisibles",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2012",
			year_of_discovery: "2014",
			genres: ["Piano; Minimalism"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	P: {
		"portico_quartet__portico_quartet": {
			lastfm_url: "https://www.last.fm/music/Portico/Portico+Quartet",
			rym_url: "https://rateyourmusic.com/release/album/portico-quartet/portico-quartet/",
			spotify_url: "https://open.spotify.com/album/6JmTEwuDRW986lE6RM6G7j?si=wv-xv-O7ROGRmPfOhBAIvg",
			year_of_release: "2012",
			genres: ["Chamber jazz; Nu jazz; Downtempo; Jazz"],
			my_rating: 8.0,
			my_review: "",
			year_of_discovery: "2022",
		},

		"poppy_eat": {
			lastfm_url: "https://www.last.fm/music/Poppy/EAT+(NXT+Soundtrack)",
			rym_url: "https://rateyourmusic.com/release/ep/poppy/eat/",
			spotify_url: "https://open.spotify.com/album/4vi6sZcoqMQ0C0EfqgRndL?si=yu6aSQAoTGSQmpNDBQFgMA",
			year_of_release: "2021",
			genres: ["Metalcore; Alternative metal; Nu Metal; Noise; Electropop; Screamo"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/263ef1af1dd0bea47e452cf4c75e681f.jpg#263ef1af1dd0bea47e452cf4c75e681f",
			my_rating: 9.5,
			my_review: "",
			year_of_discovery: "2021",
		},

		"plus_crier__sounds_for_the_supermarket": {
			lastfm_url: "https://www.last.fm/music/Plus+Crier/At+the+Mall",
			rym_url: "",
			youtube_url: "https://www.youtube.com/watch?v=gcU7ZlnJFPE&t=1426s&pp=ygUlcGx1c19jcmllciBzb3VuZHMgZm9yIHRoZSBzdXBlcm1hcmtldA%3D%3D",
			year_of_release: "1975",
			year_of_discovery: "2020",
			genres: ["Supermarket music; Lounge; Easy listening"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"pierre_van_dormael__mr_nobody_ost": {
			lastfm_url: "https://www.last.fm/music/Pierre+Van+Dormael/Mr.+Nobody+OST",
			rym_url: "",
			youtube_url: "https://www.youtube.com/watch?v=7XgnWkbo4Cg&t=1125s&pp=ygUncGllcnJlX3Zhbl9kb3JtYWVsIG1yIG5vYm9keSBzb3VuZHRyYWNr",
			year_of_release: "2009",
			year_of_discovery: "2022",
			genres: ["Film soundtrack; Modern classical"],
			my_rating: 9.5,
			my_review: "",
		},
		
		"pendulum__in_silico": {
			lastfm_url: "https://www.last.fm/music/Pendulum/In+Silico",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2008",
			year_of_discovery: "2009",
			genres: ["Drum and bass; Electronic rock; Alternative dance; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"pvris__white_noise": {
			lastfm_url: "https://www.last.fm/music/PVRIS/White+Noise",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2POgZTMa9HwsbqB3spYCQZ?si=OHvaus_6SJSK_pIY58ZaoQ",
			year_of_release: "2014",
			year_of_discovery: "2015",
			genres: ["Dance punk; Alternative rock; Pop punk; Post-hardcore; Synthpop; Electropop; Electronic"],
			my_rating: 10,
			my_review: "",
		},
		
		"poppy__i_disagree": {
			lastfm_url: "https://www.last.fm/music/Poppy/I+Disagree",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/4uTce2w80loIu3oLnW0irN?si=YRKDBaE5QB-HzZ-1XiUV2A",
			year_of_release: "2020",
			year_of_discovery: "2021",
			genres: ["Nu metal; Riot grrrl; Industrial metal; Pop metal; Electropop; Electronic"],
			my_rating: 10,
			my_review: "",
		},

		"pendulum__hold_your_colour": {
			lastfm_url: "https://www.last.fm/music/Pendulum/Hold+Your+Colour",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2005",
			year_of_discovery: "2010",
			genres: ["Drum and bass; Breakbeat; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"portishead__dummy": {
			lastfm_url: "https://www.last.fm/music/Portishead/Dummy",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1994",
			year_of_discovery: "2021",
			genres: ["Trip hop; Chillout; Dark cabaret"],
			my_rating: 8.5,
			my_review: "",
		},

		"plaid__not_for_threes": {
			lastfm_url: "https://www.last.fm/music/Plaid/Not+for+Threes",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1997",
			year_of_discovery: "2021",
			genres: ["IDM; Ambient; Ambient techno; Trip hop; Drum and bass; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	Q: {
		"queens_of_the_stone_age__songs_for_the_deaf": {
			lastfm_url: "https://www.last.fm/music/Queens+of+the+Stone+Age/Songs+for+the+Deaf",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2002",
			year_of_discovery: "2022",
			genres: ["Stoner rock; Alternative metal; Alternative rock"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	R: {
		"radiohead__a_moon_shaped_pool":  {
			lastfm_url: "https://www.last.fm/music/Radiohead/A+Moon+Shaped+Pool",
			rym_url: "https://rateyourmusic.com/release/album/radiohead/a-moon-shaped-pool/",
			spotify_url: "https://open.spotify.com/album/2ix8vWvvSp2Yo7rKMiWpkg?si=efm6w3QcSCm63RPqDAlI1Q",
			year_of_release: "2016",
			genres: ["Art rock; Chamber pop; Ambient pop; Art pop"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/28db3fdca036fb53c62754694a89d3fd.jpg#28db3fdca036fb53c62754694a89d3fd",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2016",
		},
	
		"ralph_towner__blue_sun": {
			lastfm_url: "https://www.last.fm/music/Ralph+Towner/Blue+Sun",
			rym_url: "https://rateyourmusic.com/release/album/ralph-towner/blue-sun/",
			spotify_url: "https://open.spotify.com/album/1lgXVjGzsKuDijfo10m6Nf?si=IhNMdUdMT1adGbT7dAkjag",
			year_of_release: "1982",
			genres: ["New age; ECM style jazz; Ambient; Jazz; Chamber jazz"],
			my_rating: 9.0,
			my_review: "",
			year_of_discovery: "2023",
		},
	
		"rumpistol__isola": {
			lastfm_url: "https://www.last.fm/music/Rumpistol/Isola",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Downtempo; Modern classical; Post-minimalism; Piano; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"radiohead__in_rainbows": {
			lastfm_url: "https://www.last.fm/music/Radiohead/In+Rainbows",
			rym_url: "https://rateyourmusic.com/release/album/radiohead/in-rainbows/",
			spotify_url: "https://open.spotify.com/album/5vkqYmiPBYLaalcmjujWxK?si=v40axMugSx-FQt93Uv5njg",
			year_of_release: "2007",
			genres: ["Art rock; Dream pop; Art pop; Alternative rock"],
			custom_cover_url: "https://m.media-amazon.com/images/I/A1MwaIeBpwL._UF894,1000_QL80_.jpg",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2017",
		},

		"ratatat__classics": {
			lastfm_url: "https://www.last.fm/music/Ratatat/Classics",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2006",
			year_of_discovery: "2014",
			genres: ["Indie rock; Alternative rock; Neo-psychedelia; Electronic"],
			my_rating: 9.0,
			my_review: "",
		},

		"richard_dawson__the_ruby_cord": {
			lastfm_url: "https://www.last.fm/music/Richard+Dawson/The+Ruby+Cord",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Folk; Progressive folk; Chamber folk; Post-rock; Art rock; Singer-songwritter"],
			themes: ["Contemplative", "Existential"],
			my_rating: 8.0,
			my_review: "",
		},

		"richard_dawson__2020": {
			lastfm_url: "https://www.last.fm/music/Richard+Dawson/2020",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2019",
			year_of_discovery: "2023",
			genres: ["Progressive folk; Folk; Singer-songwritter"],
			themes: ["Newcastle", "Geordie dialect"],
			my_rating: 9.0,
			my_review: "",
		},

		"revocation__teratogensis": {
			lastfm_url: "https://www.last.fm/music/Revocation/Scion+Av+Presents:+Revocation+%22Teratogensis%22",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2012",
			year_of_discovery: "2021",
			genres: ["Technical death metal; Death metal; Thrash metal"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"run_the_jewels__rtj4": {
			lastfm_url: "https://www.last.fm/music/Run+the+Jewels/RTJ4",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2020",
			year_of_discovery: "2020",
			genres: ["Hip-Hop; Rap"],
			my_rating: 9.0,
			my_review: "",
		},

		"regina_spektor__remember_us_to_life": {
			lastfm_url: "https://www.last.fm/music/Regina+Spektor/Remember+Us+to+Life",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2013",
			year_of_discovery: "2021",
			genres: ["Chamber pop; Piano rock; Indie pop; Piano; Singer-songwritter"],
			my_rating: 8.5,
			my_review: "",
		},

		"radiohead__ok_computer": {
			lastfm_url: "https://www.last.fm/music/Radiohead/OK+Computer",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1997",
			year_of_discovery: "2016",
			genres: ["Alternative rock; Post-britpop"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	S: {
		"steven_wilson__hand_cannot_erase": {
			lastfm_url: "https://www.last.fm/music/Steven+Wilson/Hand+Cannot+Erase",
			rym_url: "https://rateyourmusic.com/release/album/steven-wilson/hand-cannot-erase/",
			spotify_url: "https://open.spotify.com/album/6P7vL4vGgyrD7q9VR9BcnV?si=EZ3GpTPNS0CurlF1ikzomg",
			year_of_release: "2015",
			genres: ["Progressive Rock; Art rock; Pop rock; Alternative rock"],
			my_rating: 8.5,
			my_review: "",
			year_of_discovery: "2023",
		},

		"system_of_a_down__hypnotise": {
			lastfm_url: "https://www.last.fm/music/System+of+a+Down/Hypnotize",
			rym_url: "https://rateyourmusic.com/release/album/system-of-a-down/hypnotize/",
			spotify_url: "https://open.spotify.com/album/3QxX3NbWyLlLG6lP1xveL3?si=n_AwZVu8Tv6txWmdVNNE9w",
			year_of_release: "2005",
			genres: ["Alternative Metal; Avant-garde Metal"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/a96a0ff1cd9b384659b7edac19dc15b6.jpg#a96a0ff1cd9b384659b7edac19dc15b6",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2010",
		},
	
		"sufjan_stevens__carrie_and_lowell": {
			lastfm_url: "https://www.last.fm/music/Sufjan+Stevens/Carrie+&+Lowell",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/64xtjfsPHNHch0CZ7fPTjS?si=J-lGTRtFRvy3ST9x0gdNoQ",
			year_of_release: "2015",
			year_of_discovery: "2021",
			genres: ["Indie folk; Chamber folk; Singer-songwritter"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"system_of_a_down__system_of_a_down": {
			lastfm_url: "https://www.last.fm/music/System+of+a+Down/System+of+a+Down",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3sSfjX4fhZonjyZ10x0l0f?si=B_JycSCqTjeFojwTn6Ar7Q",
			year_of_release: "1998",
			year_of_discovery: "2011",
			genres: ["Avant-garde metal; Nu metal; Heavy metal; Alternative metal"],
			my_rating: 9.5,
			my_review: "",
		},
			
		"system_of_a_down__steal_this_album": {
			lastfm_url: "https://www.last.fm/music/System+of+a+Down/Steal+This+Album!",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/6lA1sGw7eCv27bcpd5E0wT?si=NLItOA19RuGI9ePvq09Q4g",
			year_of_release: "2002",
			year_of_discovery: "2011",
			genres: ["Nu metal; Heavy metal; Alternative metal; Avant-garde metal"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"system_of_a_down__mezmerize": {
			lastfm_url: "https://www.last.fm/music/System+of+a+Down/Mezmerize",
			rym_url: "https://rateyourmusic.com/release/album/system-of-a-down/mezmerize/",
			spotify_url: "https://open.spotify.com/album/0cn6MHyx4YuZauaB7Pb66o?si=QhPBwwzXSaizJVqewya15Q",
			year_of_release: "2005",
			genres: ["Alternative metal; Avant-garde Metal; Heavy metal; Nu metal"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/a96a0ff1cd9b384659b7edac19dc15b6.jpg#a96a0ff1cd9b384659b7edac19dc15b6",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2010",
		},

		"sleepwave__broken_compass": {
			lastfm_url: "https://www.last.fm/music/Sleepwave/Broken+Compass",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2014",
			year_of_discovery: "2016",
			genres: ["Metalcore; Alternative rock; Industrial metal; Post-hardcore; Post-grunge"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"sing_street__sing_street_soundtrack": {
			lastfm_url: "https://www.last.fm/music/Sing+Street/Sing+Street+(Original+Motion+Picture+Soundtrack)",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2022",
			genres: ["Film soundtrack; New wave; Synthpop; Indie pop; Pop"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"scntfc__oxenfree": {
			lastfm_url: "https://www.last.fm/music/scntfc/Oxenfree",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2016",
			year_of_discovery: "2017",
			genres: ["Video game soundtrack; Ambient; Downtempo"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"sheena_ringo__shoso_strip": {
			lastfm_url: "https://www.last.fm/music/%E6%A4%8E%E5%90%8D%E6%9E%97%E6%AA%8E/%E5%8B%9D%E8%A8%B4%E3%82%B9%E3%83%88%E3%83%AA%E3%83%83%E3%83%97",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/0QWI6wd3QBiQscVpBu6kUE?si=6uF4Y50sRVWVsA3p8ZALSw",
			year_of_release: "2000",
			year_of_discovery: "2022",
			genres: ["J-rock; Alternative rock; J-pop; Kayokyoku"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"system_of_a_down__toxicity": {
			lastfm_url: "https://www.last.fm/music/System+of+a+Down/Toxicity",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/6jWde94ln40epKIQCd8XUh?si=NPvbrcRHTNW4Ic_9f3xS0Q",
			year_of_release: "2001",
			year_of_discovery: "2011",
			genres: ["Nu metal; Heavy metal; Alternative metal; Avant-garde metal"],
			my_rating: 9.0,
			my_review: "",
		},

		"spiritbox__eternal_blue": {
			lastfm_url: "https://www.last.fm/music/Spiritbox/Eternal+Blue",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2021",
			year_of_discovery: "2021",
			genres: ["Djent; Alternative metal; Metalcore; Post-metal"],
			my_rating: 9.0,
			my_review: "",
		},

		"sufjan_stevens__ilinois": {
			lastfm_url: "https://www.last.fm/music/Sufjan+Stevens/Illinois",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2005",
			year_of_discovery: "2021",
			genres: ["Chamber pop; Baroque pop; Indie folk"],
			my_rating: 8.0,
			my_review: "",
		},

		"sam_gellaitry__escapism_iii": {
			lastfm_url: "https://www.last.fm/music/Sam+Gellaitry/Escapism+III",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2022",
			year_of_discovery: "2022",
			genres: ["Dubstep; Future bass; Drum and bass; Electronic"],
			my_rating: 8.5,
			my_review: "",
		},
		
		"slipknot__slipknot": {
			lastfm_url: "https://www.last.fm/music/Slipknot/Slipknot",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1999",
			year_of_discovery: "2009",
			genres: ["Nu metal; Alternative metal"],
			themes: ["Angsty", "Rebellious"],
			my_rating: 8.5,
			my_review: "",
		},

		"sigur_ros__agaetis_byrjun": {
			lastfm_url: "https://www.last.fm/music/Sigur+R%C3%B3s/Agaetis+Byrjun",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1999",
			year_of_discovery: "2022",
			genres: ["Post-rock; Ambient; Minimalism"],
			my_rating: 9.0,
			my_review: "",
		},
	},

	T: {
		"telegraph__mir": {
			lastfm_url: "https://www.last.fm/music/Telegraph/Mir",
			rym_url: "https://rateyourmusic.com/release/album/telegraph/mir/",
			year_of_release: "2018",
			genres: ["Progressive rock; Space rock; Psychedelic Rock; Post-rock; Radio broadcast recordings; Electronic"],
			my_rating: 9.0,
			my_review: "",
			year_of_discovery: "2024",
		},

		"takashi_kako__ritual_ost": {
			lastfm_url: "https://www.last.fm/music/Takashi+Kako/Shiki+Jitsu+(be+happy.+be+happy.+be+happy)",
			rym_url: "https://rateyourmusic.com/release/album/takashi-kako/be-happy_be-happy_be-happy/",
			youtube_url: "https://www.youtube.com/watch?v=sgCACktwy5k&t=50s&pp=ygUedGFrYXNoaSBrYWtvIHJpdHVhbCBzb3VuZHRyYWNr",
			artist_name_Japanese: "加古隆",
			year_of_release: "2000",
			genres: ["Film soundtrack; Neo-classical new age; Ambient; Piano"],
			my_rating: 9.5,
			my_review: "",
			year_of_discovery: "2023",
		},
	
		"thom_yorke__suspiria": {
			lastfm_url: "https://www.last.fm/music/Thom+Yorke/Suspiria",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/2UehMLybYgLuuNHRNJpbCB?si=T7o80JKFRGCkDuw82c7d0Q",
			year_of_release: "2012",
			year_of_discovery: "2021",
			genres: ["Ambient; Ambient pop; Alternative folk; Chamber pop"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"twenty_one_pilots__vessel": {
			lastfm_url: "https://www.last.fm/music/twenty+one+pilots/Vessel+(Bonus+Tracks+Version)",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/14onjcwGXJFQnTmmCnTUfQ?si=n6974t5pTvyloWzgWzWVPg",
			year_of_release: "2013",
			year_of_discovery: "2015",
			genres: ["Pop; Hip-Hop; Pop rap; Alternative pop; Emo"],
			themes: ["Upbeat"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"tkay_maidza__last_year_was_weird_vol_2": {
			lastfm_url: "https://www.last.fm/music/Tkay+Maidza/Last+Year+Was+Weird,+Vol.+2",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2020",
			year_of_discovery: "2020",
			genres: ["Hip-Hop; Rap; R&B; Pop rap; Neo-soul"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"takashi_kako__wind_waltz": {
			lastfm_url: "https://www.last.fm/music/Takashi+Kako/%E9%A2%A8%E3%81%AE%E3%83%AF%E3%83%AB%E3%83%84",
			rym_url: "",
			spotify_url: "",
			artist_name_Japanese: "加古隆",
			year_of_release: "2002",
			year_of_discovery: "2023",
			genres: ["Piano; Neo-classical new age; Modern classical"],
			my_rating: 9.0,
			my_review: "",
		},
		
		"tyler_the_creator__flower_boy": {
			lastfm_url: "https://www.last.fm/music/Tyler,+the+Creator/Flower+Boy",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2017",
			year_of_discovery: "2018",
			genres: ["Hip-Hop; Rap; Neo-soul; Soul; Pop rap"],
			my_rating: 9.0,
			my_review: "",
		},

		"thelonious_monk__monks_music": {
			lastfm_url: "https://www.last.fm/music/+noredirect/Thelonious+Monk+Septet/Monk%27s+Music",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1957",
			year_of_discovery: "2021",
			genres: ["Jazz; Hard bop"],
			my_rating: 9.0,
			my_review: "",
		},	
	},

	W: {
		"worlds_end_girlfriend__hurtbreak_wonderland": {
			custom_cover_url: require('../websiteContent/albums/worlds_end_girlfriend__hurtbreak_wonderland/album_cover.jpg'),
			lastfm_url: "https://www.last.fm/music/World%27s+End+Girlfriend/Hurtbreak+Wonderland",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/7KtBhRWitpnHoma8UWiDgz?si=dhQ99k1YT3-tdBWS46M7GA",
			year_of_release: "2007",
			genres: ["Post-Rock; Modern Classical; IDM; Breakcore; Glitch; Chamber jazz; Electronic"],
			my_rating: 8.0,
			my_review: "",
			year_of_discovery: "2023",
		},

		"ween__the_mollusk": {
			lastfm_url: "https://www.last.fm/music/Ween/The+Mollusk",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1997",
			year_of_discovery: "2013",
			genres: ["Psychedelic Rock; Psychedelic Pop; Neo-Psychedelia; Comedy rock; Art rock"],
			themes: ["Weird", "Quirky"],
			my_rating: 8.0,
			my_review: "",
		},
	},

	V: {
		"vale_smith__coruscate": {
			lastfm_url: "https://www.last.fm/music/Vale-Smith/Coruscate",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2021",
			year_of_discovery: "2021",
			genres: ["Future bass; EDM Trap; EDM; IDM; Wonky; Glitch pop; Electronic"],
			my_rating: 8.0,
			my_review: "",
		},
	},

	X: {
		"xtc__oranges_and_lemons": {
			lastfm_url: "https://www.last.fm/music/XTC/Oranges+&+Lemons",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3suXBde2fATz1UzA6f7UoA?si=WuZJk8R6T_WLHBzehng56w",
			year_of_release: "1999",
			year_of_discovery: "2018",
			genres: ["New wave; Psychedelic pop; Baroque pop; Art pop; Art rock; Chamber pop"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"xtc__nonsuch": {
			lastfm_url: "https://www.last.fm/music/XTC/Nonsuch",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/6WK4H6AhFAt4RhuTzLFJws?si=aq2mf8EIQiuG_4tGyuIxyQ",
			year_of_release: "1992",
			year_of_discovery: "2013",
			genres: ["New wave; Baroque pop; Jangle pop"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"xtc__apple_venus": {
			lastfm_url: "https://www.last.fm/music/XTC/Apple+Venus+Volume+1",
			rym_url: "",
			youtube_url: "",
			year_of_release: "1999",
			year_of_discovery: "2014",
			genres: ["Symphonic pop; New wave; Pop; Progressive pop"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"xtc__go_2": {
			lastfm_url: "https://www.last.fm/music/XTC/Go+2",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1978",
			year_of_discovery: "2013",
			genres: ["New wave; Post-punk; Art punk"],
			my_rating: 9.0,
			my_review: "",
		},	
		
		"xtc__nonsuch": {
			lastfm_url: "https://www.last.fm/music/XTC/Nonsuch",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/6WK4H6AhFAt4RhuTzLFJws?si=aq2mf8EIQiuG_4tGyuIxyQ",
			year_of_release: "1992",
			year_of_discovery: "2013",
			genres: ["New wave; Baroque pop; Jangle pop"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"xtc__apple_venus": {
			lastfm_url: "https://www.last.fm/music/XTC/Apple+Venus+Volume+1",
			rym_url: "",
			youtube_url: "",
			year_of_release: "1999",
			year_of_discovery: "2014",
			genres: ["Symphonic pop; New wave; Pop; Progressive pop"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"xtc__go_2": {
			lastfm_url: "https://www.last.fm/music/XTC/Go+2",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1978",
			year_of_discovery: "2013",
			genres: ["New wave; Post-punk; Art punk"],
			my_rating: 9.0,
			my_review: "",
		},
	
		"xtc__skylarking": {
			lastfm_url: "https://www.last.fm/music/XTC/Skylarking",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/3FVsJiQMI7dp0RfTBdWtMW?si=fD1rW8LqRkqWVANm_9Tuuw",
			year_of_release: "1986",
			year_of_discovery: "2013",
			genres: ["New wave; Psychedelic pop; Baroque pop; Art pop; Art rock; Chamber pop"],
			my_rating: 9.5,
			my_review: "",
		},	
	
		"xtc__mummer": {
			lastfm_url: "https://www.last.fm/music/XTC/Mummer",
			rym_url: "https://rateyourmusic.com/release/album/xtc/mummer/",
			spotify_url: "https://open.spotify.com/album/7jArveDNywiBbEqax0f2vn?si=H4JmBO3yRkKNHZdt2xQ3PA",
			year_of_release: "2011",
			genres: ["Art punk; New wave; Art rock; Psychdelic pop; Neo-Psychedelia"],
			my_rating: 10,
			custom_cover_url: "https://beatopolis.files.wordpress.com/2019/01/xtc-1.jpg?w=640",
			year_of_discovery: "2013"
		},
	
		"xtc__chips_from_the_chocolate_fireball": {
			lastfm_url: "https://www.last.fm/music/The+Dukes+Of+Stratosphear/Chips+From+The+Chocolate+Fireball",
			rym_url: "https://rateyourmusic.com/release/comp/the-dukes-of-stratosphear/chips-from-the-chocolate-fireball/",
			spotify_url: "https://open.spotify.com/album/46ZRujqytRXcbgloCKA9Q7?si=gOZzfJVORiWtrjWrtb1Lug",
			year_of_release: "1987",
			genres: ["Psychedelic Rock; Psychedelic Pop; Jangle pop; New wave"],
			custom_cover_url: "https://lastfm.freetls.fastly.net/i/u/770x0/42a3dd8c1dea4f35b3c0711eb02c1a9d.jpg#42a3dd8c1dea4f35b3c0711eb02c1a9d",
			my_rating: 10,
			my_review: "",
			year_of_discovery: "2012",
		},
	},

	Y: {
		"yes__fly_from_here": {
			lastfm_url: "https://www.last.fm/music/Yes/Fly+From+Here",
			rym_url: "https://rateyourmusic.com/release/album/yes/fly-from-here/",
			youtube_url: "https://www.youtube.com/watch?v=SEs-i9kMpKg",
			custom_cover_url: require('../websiteContent/albums/yes-fly_from_here/custom_album_cover.jpg'),
			year_of_release: "2011",
			genres: ["Progressive rock; Symphonic prog; Progressive pop"],
			my_rating: 10,
			my_review: ReactDomServer.renderToString(YesFlyFromHereReview()),
			year_of_discovery: "2013"
		},
	
		"yes__close_to_the_edge": {
			lastfm_url: "https://www.last.fm/music/Yes/Close+To+The+Edge+(Deluxe+Edition)",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/6344rkGqCBDenGoS7eJlBN?si=mgSZFJRdT-K2ehLiwK91tQ",
			year_of_release: "1972",
			year_of_discovery: "2013",
			genres: ["Progressive rock; Symphonic rock"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"yellow_magic_orchestra__solid_state_survivor": {
			lastfm_url: "https://www.last.fm/music/Yellow+Magic+Orchestra/Solid+State+Survivor",
			rym_url: "",
			spotify_url: "https://open.spotify.com/album/5TmpFE7Xus70ko1QYGxFIe?si=Vhnh4CGMSmGTUQSAtz8Mew",
			year_of_release: "1979",
			year_of_discovery: "2018",
			genres: ["Synthpop; New wave; Techno"],
			my_rating: 9.5,
			my_review: "",
		},
	
		"yu_mikaye__katamari_damacy_soundtrack": {
			lastfm_url: "https://www.last.fm/music/Yu+Miyake/Katamari+Damacy+Soundtrack+%22Katamari+Fortissimo+Damacy%22",
			rym_url: "",
			youtube_url: "https://www.youtube.com/watch?v=QAA6hq9RL-4&t=16s&pp=ygUleXVfbWlrYXllX19rYXRhbWFyaV9kYW1hY3lfc291bmR0cmFjaw%3D%3D",
			year_of_release: "2004",
			year_of_discovery: "2021",
			genres: ["Video game soundtrack; J-pop; Shibuya-kei; Synthpop; Jazz pop; Salsa; Funk"],
			my_rating: 9.5,
			my_review: "",
		},

		"yuriko__nakamura__wind_and_reflections": {
			lastfm_url: "https://www.last.fm/music/%E4%B8%AD%E6%9D%91%E7%94%B1%E5%88%A9%E5%AD%90/%E9%A2%A8%E3%81%AE%E9%8F%A1",
			rym_url: "",
			spotify_url: "",
			year_of_release: "1987",
			year_of_discovery: "2023",
			genres: ["New Age; Ambient; Neoclassical New Age; Piano"],
			my_rating: 8.5,
			my_review: "",
		},

		"yellow_magic_orchestra__ymo": {
			lastfm_url: "https://www.last.fm/music/Yellow+Magic+Orchestra/YMO",
			rym_url: "",
			spotify_url: "",
			year_of_release: "2011",
			year_of_discovery: "2018",
			genres: ["Synthpop; Electronic"],
			my_rating: 8.5,
			my_review: "",
		},
	},
}

export const album_reviews = convert_collection_of_json_objects_to_one_list_grouped_by_letters(database);
